### ISSUE TITLE
[Issue] White Blank Space

### ISSUE THREAD

**Issue by asteroidb12** [tom5454/CustomPlayerModels#1]
This mod is great mod to make custom models. However, there's a small problem in the Texture section. There's a panel in which I can edit the skin but it's just white blank space and it stays like that.

The screenshot:
![Minecraft 1 7 10 Definitive Edition 01_02_2021 11_37_54 a  m](https://user-images.githubusercontent.com/68461874/106509631-b7f8e400-6482-11eb-9f19-0b98c45b41d3.png)

**Comment by tom5454** [comment]
What Minecraft version are you using?

**Comment by asteroidb12** [comment]
I am using Minecraft 1.16.5

**Comment by tom5454** [comment]
Should be fixed in the new version.
