### ISSUE TITLE
I have no idea how to export the 3D skin

### ISSUE THREAD

**Issue by McSkellyHo** [tom5454/CustomPlayerModels#10]
It would be nice to have some step by step tutorial for this mod, figuring out how to even edit in it was hard enough. I pasted the text the export gave me into a gist, and I wrote in the URL of my gist (because ctrl shortcuts crash the game) but it said unknown URL, I checked many times to see if I wrote it right and I did. Is there an easier way to export and use the 3D skin?

**Comment by tom5454** [comment]
Please send in your crash report, the game shouldn't crash with pasting a link.

**Comment by McSkellyHo** [comment]
[crash-2021-02-11_20.51.24-client.txt](https://github.com/tom5454/CustomPlayerModels/files/5968059/crash-2021-02-11_20.51.24-client.txt)
 This is the whole crash report, it crashes the whole game whenever I use any keyboard shortcut involving the ctrl or shift key as soon as I press down any other key while holding one of those two.

**Comment by tom5454** [comment]
Your game crashes because of this: grondag/fermion#2 you have to update your mods, or try using the editor in a new install by itself without any other mods installed.
You are using an outdated version of https://www.curseforge.com/minecraft/mc-mods/exotic-matter-library you should probably update that.

**Comment by McSkellyHo** [comment]
I don't have that mod, but I do have an outdated version of https://www.curseforge.com/minecraft/mc-mods/exotic-blocks which requires it, though the exotic blocks mod works in the game. I'll get the newest version of both and then inform you if it works after that.

**Comment by McSkellyHo** [comment]
I was able to paste the link fine now. It was that mod causing the problems, I still don't understand how to actually use the 3D skin. I uploaded the exported png as my skin but it was just the vanilla skin without the 3D objects I added in the editor. Am I supposed to do something specific during the export?

**Comment by tom5454** [comment]
You probably have to update to the latest version of Customizable Player Models due to a skin loading bug.

**Comment by McSkellyHo** [comment]
I went for the latest 1.16 file since I run fabric on 1.16.4. I'll try the mod version for 1.17, the very newest one

**Comment by tom5454** [comment]
The 1.16 version is fine, the 1.17 one wont load under 1.16.4

**Comment by McSkellyHo** [comment]
It says "unable to load skin" in the skin changer in the launcher when I tried to use the on I put the exported png on. The preview of it shows just the normal vanilla skin without the slight texture changes I made in the editor.

**Comment by tom5454** [comment]
If you edit your skin in the editor it won't show up in the minecraft launcher, the modified skin is in the gist file, with your model parts.

**Comment by McSkellyHo** [comment]
When I try to load the one from the exported png, it says that it was unable to load it and when I go into a world, my skin is still normal.

**Comment by tom5454** [comment]
Please post the exported png.

**Comment by McSkellyHo** [comment]
![MATTIE 3](https://user-images.githubusercontent.com/78847349/107697265-4c4d1d00-6cb3-11eb-9cfe-830655e157d6.png)

**Comment by tom5454** [comment]
Try restarting your launcher, mine accepts it.

**Comment by McSkellyHo** [comment]
It works now! Thanks so much for the help! I'll close the issue now, thanks again!
