### ISSUE TITLE
Animation previews are broken in the editor in 1.16 mod version forge 0.0.16a

### ISSUE THREAD

**Issue by Xigzagamer** [tom5454/CustomPlayerModels#101]
When you hit play to test an animation in the editor none of the parts will move, but visibility will still toggle properly. This doesn't affect the ingame animations which play properly and have had the bug with visibility toggling fixed.

**Comment by Nues** [comment]
In my case, the default animations and positions overwrited my custom animations in the editor even though they test fine in-game, which makes any further editing to my custom animations super tedious.
