### ISSUE TITLE
Crash: Tried to create RedirectHolder for unknown model type(s)

### ISSUE THREAD

**Issue by SonicCraft** [tom5454/CustomPlayerModels#105]
I tried updating the mod to 0.0.17c in this custom modpack. (version 2.0.4): https://www.curseforge.com/minecraft/modpacks/dragonspire-reborn-techno-edition
anyway as soon as I tried to join the server the client would crash. Crash logs below.
[crash-2021-07-17_15.42.44-client.txt](https://github.com/tom5454/CustomPlayerModels/files/6835225/crash-2021-07-17_15.42.44-client.txt)
[crash-2021-07-17_15.45.52-client.txt](https://github.com/tom5454/CustomPlayerModels/files/6835226/crash-2021-07-17_15.45.52-client.txt)

**Comment by Thesekar** [comment]
Same issue here; occurs with all biped mobs (zombies, husks, skeletons, players) when trying to wear armor. Narrowed down offending mod to this one with testing.

Don't know if this is an incompatibility with another mod, so I've attached a crash log.
[crash-2021-07-18_12.36.21-client.txt](https://github.com/tom5454/CustomPlayerModels/files/6836706/crash-2021-07-18_12.36.21-client.txt)
Error resolved clientside by removing CPM from load order.

**Comment by Reginald-Halifrax** [comment]
I hate to be one of those guys that just say "bump" but I can confirm I'm another _player_ dealing with this issue after version 17, always when trying to render clothing items on mobs.

**Comment by InmoNum** [comment]
Bump ~ Bump >_>
Happened to me only on a server, worked fine in singleplayer
