### ISSUE TITLE
Pose Animation Glitch with Duration More than 30-35 Seconds

### ISSUE THREAD

**Issue by Cynadyde** [tom5454/CustomPlayerModels#108]
I'm using CustomPlayerModels-1.16-0.0.17c

[cynavali_fixing_sleep_pos_0.zip](https://github.com/tom5454/CustomPlayerModels/files/6836866/cynavali_fixing_sleep_pos_0.zip)

In the editor, the model's sleeping pose looks fine.
When I test in-game, it is glitched:
- all the parts under head and chest are reset to default 
- the pose does not reset for a few moments after exiting the bed
- Clicking reset pose does not have an effect

The animation element that causes this issue is Pose: Ears (Sleeping).
(230 frames, 40000ms, on frame 11, Ear Top Right has a rotation of [8, 0, 0])
When I remove this, the sleeping pose works how it should.
When I delete the part and recreate it exactly, it causes the same issue.
I remade the part with only 30000ms duration and it worked; however, with 35000ms it was glitched again.

**Comment by tom5454** [comment]
The duration is stored as a short when exported, the upper limit is 32767ms, higher values end up being negative and breaks the animation handler.
