### ISSUE TITLE
Duplicating Model Parts Unexpected Behavior 0.0.17d

### ISSUE THREAD

**Issue by SonicCraft** [tom5454/CustomPlayerModels#114]
This bug makes duplicating quite unusable in 0.0.17d.
It is hard to explain so I will attach a video link showing the issue
[The Issue](https://youtu.be/GtGAFKKCx7w)

**Comment by Orgamorsh** [comment]
I also have this issue and would like to add that when moving these parts, you seem to get two of the same part. Clicking on one will select both of them. Deleting the broken part, saving, then reloading the project a couple of times seems to fix it.
