### ISSUE TITLE
using templates button in github does nothing when clicked 

### ISSUE THREAD

**Issue by Joshernoob** [tom5454/CustomPlayerModels#12]
when using the using templates button it does nothing in the github meaning there no way to see how to use them

**Comment by tom5454** [comment]
Templates are not implemented yet

**Comment by Joshernoob** [comment]
understood then

**Comment by Joshernoob** [comment]
trying to use the exported .cmpproject there anywere that show how

**Comment by Joshernoob** [comment]
will help to know how to use them or the animations themself as there nothing on the wiki here

**Comment by tom5454** [comment]
I'm working on the wiki. You have to export the model to use it in world: https://github.com/tom5454/CustomPlayerModels/wiki/Exporting
