### ISSUE TITLE
Horizontal Planes Treated Like Cuboids

### ISSUE THREAD

**Issue by Creepopolous** [tom5454/CustomPlayerModels#124]
I am trying to texture a plane, but as I did so, I discovered that it was mirroring the texture diagonally. After some testing, it appeared that the editor believed it was a cuboid, and what I was seeing was the back of the opposite face. This did not occur when the plane was along the X or Z axis. ![Screenshot 2021-08-11 114451](https://user-images.githubusercontent.com/13527758/129085788-f77f28a8-fbc5-45f5-8ba4-2e24626c5a46.png)

**Comment by tom5454** [comment]
Enable `Effects/Single Texture` to make planes.
