### ISSUE TITLE
Custom Armor Helmet glitch | BUG

### ISSUE THREAD

**Issue by SonicCraft** [tom5454/CustomPlayerModels#129]
It seems its only in the editor this glitch appears.
Root selected:
![Screenshot 2021-08-23 183710](https://user-images.githubusercontent.com/39831475/130530939-e4cdf6b4-5200-4c7b-9a2f-27fde4ea9e4b.png)
Helmet selected:
![Screenshot 2021-08-23 183640](https://user-images.githubusercontent.com/39831475/130531067-e80258b3-01cf-49c1-9f68-1b1974e8760b.png)
Helmet selected but hidden:
![Screenshot 2021-08-23 183731](https://user-images.githubusercontent.com/39831475/130531093-d20688d9-2e4b-4e3d-ba28-ebdeea541e55.png)

This makes it a bit difficult for me to edit my model's armor placement for the helmet.
Version: Forge 0.0.17g

**Comment by tom5454** [comment]
Does this happen in the latest version?
