### ISSUE TITLE
Custom Armor Chestplate glitch | BUG... i think

### ISSUE THREAD

**Issue by SonicCraft** [tom5454/CustomPlayerModels#130]
When selecting the chestplate to edit it, I noticed that the shoulders are separate:
![chestonly](https://user-images.githubusercontent.com/39831475/130532222-6c5a8b08-75a7-4f35-9111-c3515c70c0fa.png)
however, when I selected the right shoulder part, the center part didn't hide:
![chestright](https://user-images.githubusercontent.com/39831475/130532412-049bc97c-7c14-40fb-b030-36cabceba90f.png)
It became worse when I selected the Left shoulder part:
![chestleft](https://user-images.githubusercontent.com/39831475/130532494-85bbe736-8590-4aba-84fd-a3b16d8d1551.png)
I don't know if this is intentional or not, I just thought I would report it just in case.
Version: Forge 0.0.17g

**Comment by tom5454** [comment]
Does this happen in the latest version?
