### ISSUE TITLE
Armor bug

### ISSUE THREAD

**Issue by Callu342** [tom5454/CustomPlayerModels#131]
i dont know what is going on here

https://user-images.githubusercontent.com/76173715/131213654-93db8416-cb6d-4ae9-81ac-47d2a1c729a8.mp4

**Comment by tom5454** [comment]
Please test it with 0.1.0a if the issue still exists please post your project file.

**Comment by Callu342** [comment]
sorry for the wait, i forgot about this!
when i clear their frames, everything seems to work!
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/76173715/133922799-24d09937-8e32-4e5d-b168-860f8c420043.gif)
