### ISSUE TITLE
Can't see outer layer of my skin?

### ISSUE THREAD

**Issue by breakingbinary** [tom5454/CustomPlayerModels#132]
I had added ears to my skin but whenever I go to test it or use it, the outer layer doesn't show. I used The Skindex to make it and have other mods active at the time of using this current one

**Comment by Oakstar519** [comment]
Did you add the second layer of your skin? The editor is pretty much WYSIWYG, and it doesn't add the second layer when you open a skin for the first time, so you have to manually add it.
