### ISSUE TITLE
changing skin/model using menu or hotkey

### ISSUE THREAD

**Issue by cs234477** [tom5454/CustomPlayerModels#136]
Idk if anyone has posted about this, but how do I use the menu that comes with the mod to switch skins in-game? i keep having to go into skin editor, finding the skin and hit test in game, I would really like it if some one could tell me how to put the skins/moddels on the menu list so I can quickly switch between them when I want.

**Comment by Oakstar519** [comment]
Stick them in .minecraft\player_models

**Comment by cs234477** [comment]
well I did but I mean, how do I put them on the list below in the pic


![Screenshot (6)](https://user-images.githubusercontent.com/90009319/132134016-61b78b78-2080-49cf-9c68-67e0f34ca62a.png)

**Comment by tom5454** [comment]
You have to export using the editor under File/Export and change mode to Export: Model.
