### ISSUE TITLE
(recently) migrated to microsoft accounts cant use skins 

### ISSUE THREAD

**Issue by Ragnarockandstone** [tom5454/CustomPlayerModels#137]
friend of mine migrated thier mojang account to microsoft,now opon attempting to change skin it gives a 401 error,inticating that the credentials are invalid,if anyone has experience this issue too,or knows a solution feel free to share them,have a good day.

Image related.
![026f657577a1f6172a0248c32f7382c3](https://user-images.githubusercontent.com/86318193/132138390-ed4ace38-5876-4df7-8fff-67d22fe77217.png)

**Comment by tom5454** [comment]
Try using the latest version (0.1.1a) if it still doesn't work use your vanilla launcher to upload the skin for the first time, then it _should_ work.
