### ISSUE TITLE
Outlines rendering behind objects in latest forge 1.16.5 release

### ISSUE THREAD

**Issue by Xigzagamer** [tom5454/CustomPlayerModels#140]
I noticed that the outlines and the XYZ position thingy are rendering behind my parts making it difficult to position things.

**Comment by EnderPlaysLive** [comment]
It's been a while since I made something with the mod so take this with a grain of salt, but if I were you, the first thing I would do is check what the offset is. If I remember correctly, that moves the piece you are working on away from the xyz thing.

**Comment by Xigzagamer** [comment]
That's not the problem, from what I can tell it only happens when you use the solid color setting. (Which is what I was using while prototyping the shape of my model.)
