### ISSUE TITLE
Models not showing on my end only (every version)

### ISSUE THREAD

**Issue by EnderPlaysLive** [tom5454/CustomPlayerModels#144]
Short explanation: When I use any version of the mod, the models dont show on my end and the menu to refresh the skin says an error. I cannot see my custom skin, nor any of my friends' skins.

Long explanation: I tested a bunch of stuff to try to find the source for myself but I dont know how to fix it. I'll say all the stuff I tested and give the limited knowledge conclusions I drew from them.
1. None of the versions work. Both fabric and forge, any minecraft update, even outdated versions of the mod for updates that worked before.
2. when I load a local file skin, it shows that on my end (in singleplayer or on servers with the mod installed) It also work in the same situations if I click the "test in game" option in the editor.
3. If I'm on a server with friends, both with and without the mod uploaded on the server, they can see my skin and their skin, but I cant see my own or theirs.
4. when in the gestures menu, the error given says something about "unrecognized ssl message" or something like "not available"
5. When looking in the game output log, it said something about "semver" which, when I looked it up, said something about incompatible versions which doesnt make sense because it's with all versions of the mod and many of them are scenarios that worked correctly together for a long time.
6. I use the git gist thing for the skin information storage, I dont have a skin that's small enough of a file to test otherwose, but I doubt it due to the fact that other people can see the skin i'm using.

**Comment by tom5454** [comment]
Something in your network or PC is blocking access GitHub gists. Check your antivirus or firewall if its blocking `gist.githubusercontent.com`. Also try clicking the `Raw` button on the gist page and see what comes up.
