### ISSUE TITLE
short gestures can only be triggered by pressing the keybind, twice.

### ISSUE THREAD

**Issue by Trickster-4** [tom5454/CustomPlayerModels#146]
yeah thats the bug, when I tried to make a custom gesture planned to work by only pressing a button, but apparently the keybind works as a on/off switch. this is useful for poses that can last forever like sitting for example, but it is redundant for poses and gestures like waving for example, in which it lasts for just a couple of seconds. because of that, you don't actually need to "turn it off", but the keybind pretends it is. so it is a bummer.

here's how it looks. when I press the keybind, the waving anim starts, but when I press it again while it is going, it makes it stop. since it is a short animation instead of a loop, the animation was supposed to start anytime I would press the keybind. and when it ends, I have to press the keybind twice, as if the animation was still going.

https://user-images.githubusercontent.com/90531548/133664532-123fcc39-7f26-4be4-af31-9151a57cc764.mp4

.

**Comment by tom5454** [comment]
Was implemented in 0.5.0a
