### ISSUE TITLE
[Fabric 1.17.1] mod requires fabric API but is not listed as dependecy

### ISSUE THREAD

**Issue by Scraft161** [tom5454/CustomPlayerModels#148]
installed fabric loader for 1.17.1 via multimc, then tried running the mod but didn't load.
a quick look at the log gave me ` - Mod 'Customizable Player Models' (cpm) requires any version of mod fabric, which is missing!`

am I dumb and does this mod require fabric API (which is not listed as dependency on CF page) or am I doing something else wrong.

thanks in advance Scraft161
[log file with CPM alone](https://github.com/tom5454/CustomPlayerModels/files/7402895/latest.log)

EDIT: the mod requires fabricAPI but it's not listed on the CF page

**Comment by tom5454** [comment]
Added it to the description
