### ISSUE TITLE
Allow for layers to be hidden with vanilla's skin customization settings

### ISSUE THREAD

**Issue by Scraft161** [tom5454/CustomPlayerModels#149]
Title says it all.

Allow for skin layers to be hidden with the vanilla skin customization.

Ie: when a layer is tied to a specific skin overlay and said overlay is disabled in the vanilla skin customization this layer would also be hidden.

an option for this can be added in the "Effects" menu item with checkboxes for each layer

additional anhancement:
when selecting multiple overlay layers allow for selecting between "and", "or", "xor" for when to show the cube

**Comment by tom5454** [comment]
Toggleable layers were added in 0.5.0a
