### ISSUE TITLE
Sneaking animation has unupdated/unedit frame delay or delay time before start first frame.

### ISSUE THREAD

**Issue by AshiraLOL** [tom5454/CustomPlayerModels#151]
i trying animation not in editer mode. when prass a Sneak key( And released key ). something not right. animation have 2 step!!
 
Sneaking animation has previously unupdated animation frame in between frame.
from any animation to sneaking animation, should have only 1 step. 

normal should be.
( Any animation -> Sneaking animation )

but it's like having delay between frames.
( Any animation ->  Sneaking unUpdate/delay (look like rotation not update) -> Sneaking animation )

For Test
-try to add all part to main root body.
-edit new part and do rotation made model look stand normal.
-and test you will see delay on start and end of sneaking animation.

I already try
-on/off Additive
-delete all pose but pose Sneaking
-move offset main part to center main body
nothing can fix.

*Edit
i'm test with other player in multiplayer. the sneaking animation look normal from other player.

![Capture](https://user-images.githubusercontent.com/51751845/139555312-8c0ca3b3-e5a5-4e99-9eb3-be410a43c8df.PNG)

https://user-images.githubusercontent.com/51751845/139555316-a60964be-bd2f-437b-a144-f7e73ee23405.mp4

https://user-images.githubusercontent.com/51751845/139576326-84e839e6-be79-4e5c-a195-6006c5d29b61.mp4

like root body rotation too late. or sneak animation show too early.
my eng not go well..  pls don't mind.

**Comment by DaeTheDragon** [comment]
Is this low priority?
it's been over a year now and this bug is still very annoying to see.

**Comment by DaeTheDragon** [comment]
Additionally-
This bug also occurs while falling:

https://user-images.githubusercontent.com/80906771/233689187-c1bf79f5-eebe-455f-a55a-03f1ca959b6a.mp4
