### ISSUE TITLE
how to load a custom model

### ISSUE THREAD

**Issue by VenezuelanHell** [tom5454/CustomPlayerModels#153]
help, for the last hour i tried loading a single model into minecraft, i read the wiki, i followed the steps, but there the model doesn't show up in game, yet every step is correct, im i doing somethin wrong?

**Comment by tom5454** [comment]
Use the Discord Server for tech support questions: [https://discord.gg/mKyXdEsMZD](https://discord.gg/mKyXdEsMZD)
