### ISSUE TITLE
[mixin-mod-incompat] CPM Forge - Critical injection failure with TooFast's mixin.

### ISSUE THREAD

**Issue by Cixon** [tom5454/CustomPlayerModels#159]
**Version:**
1.16.5
CustomPlayerModels-v0.1.1b

**Conflicting mod:**
Too fast - https://www.curseforge.com/minecraft/mc-mods/too-fast

**Crash-log:**
[crash-2021-12-14_18.21.24-fml.txt](https://github.com/tom5454/CustomPlayerModels/files/7715588/crash-2021-12-14_18.21.24-fml.txt)

**Comment by tom5454** [comment]
The issue is with Too fast, their mixin refmap file is corrupted. The game would still crash without CPM, when you load into a world.

**Comment by noobanidus** [comment]
For the record, this is a race-condition conflict with RandomPatches modifying a variable before my mixin is run, which causes my mixin to fail. The refmap isn't corrupted.
