### ISSUE TITLE
Armor not rendering right

### ISSUE THREAD

**Issue by SparkdotIe** [tom5454/CustomPlayerModels#161]
Players with the mod in multiplayer seem to be able to see the armor layers correctly, however on client side it renders incorrectly, looking like vanilla armor. I'm running the 1.18 mod on 1.18.1 fabric

What I see:
![2021-12-20_19 19 11](https://user-images.githubusercontent.com/26665237/146854882-fa22c939-b3ad-4b00-84ae-c669ffd06ab7.png)

What others see:
![2021-12-20_19 20 06](https://user-images.githubusercontent.com/26665237/146854955-1b173542-5049-438d-9b6e-85a2059ef8cc.png)

Mods: (from output log so many are child mods)
- ambientenvironment 7.0.3
	- appleskin mc1.18-2.2.0
	- architectury 3.2.51
	- armor_hud 0.3.5
	- armorsoundtweak 5.0.0
	- autoreconnect 1.3.2
	- beenfo 1.18-fabric0.43.1-1.3.3
	- betterf3 1.2.2
	- bettermounthud 1.1.3
	- betterthirdperson 1.5.4
	- cameraoverhaul 1.3.0-fabric-universal
	- chat_heads 0.6.0
	- chunky 1.2.153
	- clientcommands 2.6
	- clientcommands-scripting 1.3 via clientcommands
	- cloth-api 2.0.54
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-client-events-v0 2.0.54 via cloth-api
	- cloth-common-events-v1 2.0.54 via cloth-api
	- cloth-config 6.1.48
	- cloth-datagen-api-v1 2.0.54 via cloth-api
	- cloth-scissors-api-v1 2.0.54 via cloth-api
	- cloth-utils-v1 2.0.54 via cloth-api
	- com_electronwill_night-config_core 3.6.5 via armorsoundtweak
	- com_electronwill_night-config_toml 3.6.5 via armorsoundtweak
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- controlling 9.0.4
	- cpm 0.2.0a
	- craftpresence 1.8.8
	- crowdin-translate 1.4+1.18 via beenfo
	- customstars 0.7+1.18
	- damagetilt 1.18-fabric-0.1.2
	- dark-loading-screen 1.6.11
	- defaultsettings 3.1.0
	- dynamicfps 2.0.6
	- dynamicsoundfilters 1.3.0+1.18
	- easiervillagertrading 1.18-fabric0.43.1-1.5.4
	- eatinganimationid 1.2
	- entityculling 1.3.3
	- fabric 0.44.0+1.18
	- fabric-api-base 0.4.1+b4f4f6cdc8 via armorsoundtweak
	- fabric-api-lookup-api-v1 1.4.0+16d92c47c8 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a9c8 via fabric
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d95c8 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d95c8 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cdc8 via fabric
	- fabric-containers-v0 0.1.18+d154e2c6c8 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73dc8 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d95c8 via fabric
	- fabric-dimensions-v1 2.1.7+43d29571c8 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378ac8 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f17c8 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cdc8 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d95c8 via fabric
	- fabric-item-api-v1 1.3.0+691a79b5c8 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d95c8 via fabric
	- fabric-key-binding-api-v1 1.0.8+c8aba2f3c8 via fabric
	- fabric-keybindings-v0 0.2.6+b4f4f6cdc8 via fabric
	- fabric-lifecycle-events-v1 1.4.10+c15ca335c8 via armorsoundtweak
	- fabric-loot-tables-v1 1.0.8+3ac43d95c8 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d95c8 via fabric
	- fabric-mining-levels-v0 0.1.7+b4f4f6cdc8 via fabric
	- fabric-models-v0 0.3.3+3ac43d95c8 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d95c8 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cdc8 via fabric
	- fabric-object-builder-api-v1 1.11.0+3b82842ec8 via fabric
	- fabric-object-builders-v0 0.7.8+3ac43d95c8 via fabric
	- fabric-particles-v1 0.2.9+526dc1acc8 via fabric
	- fabric-registry-sync-v0 0.8.5+3ac43d95c8 via fabric
	- fabric-renderer-api-v1 0.4.9+3ac43d95c8 via fabric
	- fabric-renderer-indigo 0.4.12+3ac43d95c8 via fabric
	- fabric-renderer-registries-v1 3.2.7+b4f4f6cdc8 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d7c8 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d95c8 via fabric
	- fabric-rendering-v0 1.1.9+b4f4f6cdc8 via fabric
	- fabric-rendering-v1 1.10.3+6b21378ac8 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9514 via betterf3
	- fabric-screen-api-v1 1.0.7+3ac43d95c8 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d95c8 via fabric
	- fabric-structure-api-v1 2.0.8+295197a7c8 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d95c8 via fabric
	- fabric-textures-v0 1.0.9+3ac43d95c8 via fabric
	- fabric-tool-attribute-api-v1 1.3.4+7de09f55c8 via fabric
	- fabric-transfer-api-v1 1.5.5+b4f4f6cdc8 via fabric
	- fabricloader 0.12.11
	- fancymenu 2.4.3
	- fiber 0.23.0-2 via healthoverlay
	- firstperson 2.1.0
	- fps 1.18-1.0.2-Fabric
	- gbfabrictools 1.3.4+1.18 via beenfo
	- healthoverlay 6.0.1
	- horseinfo 0.4.1-1.18
	- illuminations 1.10.2
	- inventory_control_tweaks 1.3.12+MC1.18-1.18.1
	- inventoryprofilesnext 1.2.1
	- itemscroller 0.15.0
	- java 17
	- kirin 1.10.0-beta.2 via presencefootsteps
	- konkrete 1.3.2
	- lightoverlay 6.0.4
	- litematica 0.0.0-dev.20211203.013300
	- malilib 0.10.0-dev.26
	- minecraft 1.18.1
	- mm 2.3 via optifabric
	- multiconnect-api 1.5 via clientcommands
	- musicdr 1.0.0
	- namepain 1.4.0
	- notenoughanimations 1.4.0
	- notes 1.0.9
	- optifabric 1.12.10
	- physicsmod 2.5.18
	- pling 1.5.0
	- presencefootsteps 1.4.0
	- replanter 1.3
	- roughlyenoughitems 7.1.356
	- roughlyenoughresources 2.3.0
	- slotlock 1.0.4-BETA+1.18
	- tooltipfix 1.0.4-1.18
	- wthit 4.4.0
	- xaerominimap 21.22.5
	- xaeroworldmap 1.18.7

**Comment by Lunar-Pixel** [comment]
earlier in my testing optifabric does not work with custom armor, switched to sodium+iris and it works fine

**Comment by SparkdotIe** [comment]
Hmm, would that be something I'd need to report to Optifabric then? Sodium is fine it just doesn't have as many options as Optifine and isn't agreeing with my installation for some reason
