### ISSUE TITLE
Mod Compatibility

### ISSUE THREAD

**Issue by SubkingExtinct** [tom5454/CustomPlayerModels#162]
Hello, I've been wondering about this mod's compatibility with others. 
As far as i have searched around, i could not find an answer if this mod is compatible with others, for instance: Epic Fight mod.

I have not tested it my self but i'd like to know if there's compatibility between these mods, i am a user of CPM but i've wondered if installing them together would work, Apologies in advance if this isn't really an issue but a waste of time, i know that both mods change player models in a way and might not be compatible with each other but the question still remains.

**Comment by SonicCraft** [comment]
Epic Fight Mod completely overwrites CPM as of the last time I tested the two together. You could try it out yourself to see if something has changed.

**Comment by SubkingExtinct** [comment]
Thank you for notifying me of this, i will close this.
