### ISSUE TITLE
Vivecraft crash during game load

### ISSUE THREAD

**Issue by Raptoranim** [tom5454/CustomPlayerModels#166]
Hello, I'm trying to use the mod with Vivecraft (version 1.16.5 v7 update 8b, Forge version 1.16.5 - 36.2.20).
the version of the mod is CustomPlayerModels-1.16 v0.2.0a.

The error occurs while loading the game, and the launcher show me this:

```
The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1
```

In more detail, here's a gist that contains the crash report in detail:
https://gist.github.com/Raptoranim/469377f4dc9f05351f929d694478c2e1

**Comment by Frenxo** [comment]
ever figure it out? i have the same issue but on a different modpack, i added this mod and all of a sudden, the world would load then crash. When i get rid of the mod, it doesnt crash.
