### ISSUE TITLE
[Suggestion] Add some kind of "debug mode"

### ISSUE THREAD

**Issue by AerGameChannel** [tom5454/CustomPlayerModels#172]
Add some kind of debug mode which can be turned on in mod config (.minecraft/config/cpm.json). It would make debugging MUCH easier.

**Comment by tom5454** [comment]
There is a error log tab in the social menu, which shows if a model has loading issues. 
There is a debug mode if you add `-Dcpm.debug=true` JVM argument, it enables model loading logging.

**Comment by AerGameChannel** [comment]
Ok, thx.
