### ISSUE TITLE
[Bug-report] Custom models are not visible in multiplayer

### ISSUE THREAD

**Issue by AerGameChannel** [tom5454/CustomPlayerModels#173]
Trying to use custom model in multiplayer doesn't work, it works fine only in singleplayer. 
Mod is installed both on client and server. My friends don't see my custom model, only default player model with steve skin. No info in logs at all. Tried rejoining multiple times and one of my friends could see my custom model, everyone other including me couldn't. There is no info in logs at all except info about initializing Customizable Player Models and version-checking (both on client and server). Happens on both 1.16.5 and 1.18.1, didn't test on other versions. For 1.16.5 forge versions used: 36.2.20, 36.2.22. For 1.18.1 forge version used is 39.0.10. Mod versions are 1.16-v0.2.0a and 1.18-v0.2.0a.

**Comment by DearFox** [comment]
How exactly did you apply your model to yourself?

**Comment by AerGameChannel** [comment]
I've already fixed this bug. For some reason my github gist link i pasted while exporting model didn't work. Re-exporting the model using new github gist fixed this bug for me. Forgot to close the issue on github.
