### ISSUE TITLE
Placed player heads sometimes show default texture until updated.

### ISSUE THREAD

**Issue by Oakstar519** [tom5454/CustomPlayerModels#18]
My server (Fabric 1.16.5 with Jellysquid's mods) has a mob heads datapack, so we always have mob heads around. When placed on the ground, these heads show an Alex or Steve texture when used with this mod, which is replaced with the correct texture when broken and replaced. Occasionally they will then revert to Alex/Steve without leaving the area or unloading/reloading the chunk, but I have not been able to reproduce this consistently. The times it has happened are when I go one chunk over and can't see the heads, but it seems to be semi-random as it took several tries before it occurred.

The most consistent way of reproducing it that I found is that if the heads are here (for example):
![image](https://user-images.githubusercontent.com/57008396/108219645-eeca2d80-7103-11eb-997b-14c96135c618.png)
you can stand at the bottom of the stairs, in a different chunk, for about two minutes. However, this doesn't seem to be super reliable as sometimes it happens with less time and sometimes it doesn't happen at all. I was also unable to reproduce this in singleplayer worlds.

The heads with the mod: 
![image](https://user-images.githubusercontent.com/57008396/108218606-d279c100-7102-11eb-99b7-85a5fd9cdc97.png)

How they should look: 
![image](https://user-images.githubusercontent.com/57008396/108218629-d9a0cf00-7102-11eb-9fcc-4a7e6b3a1135.png)

**Comment by tom5454** [comment]
I have made some changes on how heads render please test this on 0.0.12a. I couldn't reproduce it on my server.
