### ISSUE TITLE
Exporting model into 3d object

### ISSUE THREAD

**Issue by KyraGhosty** [tom5454/CustomPlayerModels#182]
Hello
I was wondering if it was possible to export the created model into a 3d object that you could for exemple open in blender

In fact I’m asking this because I would love to use the model that we can create and animate with this mod using an another mod to create mini-movies, using a mod called Blockbuster

I know we can importe 3d model, so that’s why I’m asking if we can export the created model into 3d object

Thanks for taking time into reading this

**Comment by DearFox** [comment]
You can do this by simply opening the cpmproject file in Blockbench using the plugin. After that, in Blockbench you can already export the model as obj for example. But you won't be able to export animations, only geometry and UVs.
![image](https://user-images.githubusercontent.com/59219907/152055250-db7f3a15-a08f-451d-94fe-cffe98e9d5a9.png)

**Comment by KyraGhosty** [comment]
Thank you so much for answering ! This will help a lot :3
