### ISSUE TITLE
Armor behaves strangely when resizing the model.

### ISSUE THREAD

**Issue by DearFox** [tom5454/CustomPlayerModels#184]
In 0.3.0a, the function of changing the size of the player model was added (purely visual)
_Added model render transforms (Closes https://github.com/tom5454/CustomPlayerModels/issues/154)_
Thank you very much for it.
But I noticed that when resizing and shifting the model to the bottom (so that it would stand on its feet), the armor and some other parts behave strangely.
For these two models, I did not edit the armor or cape (and did not create bones for them)
![image](https://user-images.githubusercontent.com/59219907/152450182-3e0289f5-67ac-4900-bb41-9dc6cdb55b2d.png)
![image](https://user-images.githubusercontent.com/59219907/152450696-05b9c826-57ca-4ead-9066-3ebfc13bcc90.png)

**Comment by DearFox** [comment]
I seem to understand what's going on.
But I'm still not entirely sure if this is a bug or not. х)
![image](https://user-images.githubusercontent.com/59219907/152451376-864752fd-ef74-4d90-8f86-65810a291688.png)

**Comment by DearFox** [comment]
It seems that the armor still has some problems, at least the default armor.
![image](https://user-images.githubusercontent.com/59219907/152452064-0a8f8010-7532-48a4-8f69-9debb2d8ea47.png)
But if you hide it and set your own, then everything works fine х)
![image](https://user-images.githubusercontent.com/59219907/152452545-b1d43b63-e3b1-4702-a18d-5f404cd53fac.png)

**Comment by tom5454** [comment]
The scaling only works with modded parts. You have to add armor, cape, elytra, held items, then convert vanilla parts. I will add a popup for this in the editor.
