### ISSUE TITLE
Update: Model rendering on client but not on server

### ISSUE THREAD

**Issue by xArkailzx** [tom5454/CustomPlayerModels#187]
Update:
Model won't load on server but when I take the original model it works. Also, it won't load under all conditions. I tried everything and I don't really want to redo it from the beginning. The update didn't do anything.

My model on my view :

![2022-02-06_13 03 34](https://user-images.githubusercontent.com/78084119/152681744-99736087-3671-48e9-aa99-6f80787a0017.png)

Me on my friend view :

![image](https://user-images.githubusercontent.com/78084119/152681956-5ee3e341-9b87-4841-a92d-24fe476ff255.png)

 
 Original model :
 
![2022-02-06_13 07 42](https://user-images.githubusercontent.com/78084119/152681771-b645bfa5-0c2b-44bb-b9ed-9a4623c251b9.png)

_Originally posted by @xArkailzx in https://github.com/tom5454/CustomPlayerModels/issues/170#issuecomment-1030827401_

**Comment by tom5454** [comment]
Check your gist, I checked your skin model and it gives a missing gist error.
Also ask your friend to open the Gesture gui [G]/Social Settings and click on your name, it may give an error message.
