### ISSUE TITLE
Resource pack hat layer for armour not accounted for

### ISSUE THREAD

**Issue by DarkestDash** [tom5454/CustomPlayerModels#189]
The helmet itself resizes, but the hat layer for the armour does not. This is with the regular scaling, not the new pekhui scaling.
![This](https://imgur.com/a/Mgy3nq7)

**Comment by DearFox** [comment]
attached image is not displayed
![image](https://user-images.githubusercontent.com/59219907/152989862-54ec1a0e-920f-4e38-8a20-a7f8a529fd39.png)

**Comment by DarkestDash** [comment]
https://imgur.com/3PCLXfY
Hopefully that link should be better
