### ISSUE TITLE
Editor crash with Optifine

### ISSUE THREAD

**Issue by Potatoes9411** [tom5454/CustomPlayerModels#19]
![image](https://user-images.githubusercontent.com/70236001/108550694-e8cb7c80-72bc-11eb-955e-d98708ab2bf8.png)
Logs:
[latest.log](https://github.com/tom5454/CustomPlayerModels/files/6012453/latest.log)

**Comment by tom5454** [comment]
Remove optifine to use the editor. Will be fixed in the next release.

**Comment by Potatoes9411** [comment]
ok ty
