### ISSUE TITLE
Exporting cpmproject files in a curseforge profile does not allow me to load the model even in singleplayer

### ISSUE THREAD

**Issue by Halyo-Alex** [tom5454/CustomPlayerModels#194]
I tried both methods for exporting, including making the Gist for the url, and it simply does not load the model in any capacity. The only way I can use the model is the Test Ingame button, which technically works but is not useful as I want to load it for use on my realm.

What am I doing wrong?

**Comment by DearFox** [comment]
what exactly did you do?
You need to copy the code, paste it on https://gist.github.com/ , publish and copy the link you got. And paste this link into the mod.
