### ISSUE TITLE
"Glowing Eyes" parts sometimes render behind the main layer

### ISSUE THREAD

**Issue by Oakstar519** [tom5454/CustomPlayerModels#195]
Over half the time that the model loads, glowing parts render behind the main textured/colored layer. The model usually has to be reloaded several times for it to render correctly. I don't know when this started happening but it's appeared in at least the two most recent versions.

Video of the bug:
https://user-images.githubusercontent.com/57008396/153739470-ef9434e7-6484-4e24-afbd-bbe2f87508c7.mp4

**Comment by tom5454** [comment]
What is your minecraft version? Do you have Optifine or Sodium?

**Comment by Oakstar519** [comment]
Sodium and Iris in 1.16.5, 1.17.1, and 1.18.1. Doesn't occur with Optifine or just Sodium.
