### ISSUE TITLE
Crash very soon after starting loading

### ISSUE THREAD

**Issue by Darkmega18** [tom5454/CustomPlayerModels#197]
Minecraft: 1.16.5
More player Models: v0.3.1a
Pehkui: 3.1.0+1.16.5-forge.jar
Forge: 36.2.28

Game crashes moments after the loading process begins. Gives this crashlog: https://pastebin.com/nGFvVgNg

Why it happened? I'm unsure, from the last time I played with a working pack a few days ago I updated some mods:
![image](https://user-images.githubusercontent.com/8104689/154836094-f0d3e455-2557-4f16-bfd3-1a4db034446a.png)
could be any one of these.

or it could've just been an issue with the update itself. I'm unsure. Since I had to scroll down in the curseforge window to find an update for pekhui. I'm not sure if it was bugged or not, but the issue went away when I backdated more player models to 0.3.0a.

**Comment by tom5454** [comment]
The crash looks like, it is from Pehkui. In the attached screenshot you have pehkui disabled, so that's why it works.

**Comment by Darkmega18** [comment]
it was showing as enabled in curseforge once I turned player models back on. o.o
