### ISSUE TITLE
Not sure what is going on, but i can't seem to use texture.

### ISSUE THREAD

**Issue by stachmann** [tom5454/CustomPlayerModels#2]
![2021-02-04_20 49 08](https://user-images.githubusercontent.com/78576022/106980188-ba329b00-672d-11eb-94a6-d87a9b050c12.png)

**Comment by tom5454** [comment]
You have to change the parts to use textures instead of color. Click the Mode button on the left in the Model tab. I recommend changing your Gui Scale to something smaller.

**Comment by stachmann** [comment]
I see, thanks man, i got it working!
