### ISSUE TITLE
Standing Animation Prevents Export

### ISSUE THREAD

**Issue by Archytas79** [tom5454/CustomPlayerModels#20]
Having a standing animation will prevent exporting the model. It will not show the message that the export succeeded.

Replication:
Create a standing animation with at least two frames
try to export the png.

Really amazing mod, btw :)

**Comment by tom5454** [comment]
On the animation tab click the Skin Layer settings button, then press OK. This popup 'should' appear when exporting a model, and it sets up the animation exporter. Will be fixed in the next release.
