### ISSUE TITLE
Editor / Model broken on Mac

### ISSUE THREAD

**Issue by Illios42** [tom5454/CustomPlayerModels#200]
Hey, so I've been having issues with CPM after switching from 1.16.5 forge to the 1.18.1 fabric version. The editor's and gesture menu's graphics are broken and my model doesn't render (other people's models do!).

Here's the log of loading up the menu:
[latest.log](https://github.com/tom5454/CustomPlayerModels/files/8246527/latest.log)

And a pic on what the bug looks like:

<img width="2048" alt="CPMBug" src="https://user-images.githubusercontent.com/101580687/158211659-d3ec970d-13ec-41b4-a62a-bbf83ffe09e6.png">

Hope this can get fixed soon

**Comment by tom5454** [comment]
Please test the latest version (0.4.0a)
