### ISSUE TITLE
Offline Mode Servers CPM Issue/Possible Skinrestorer conflict

### ISSUE THREAD

**Issue by AriaThePeryton** [tom5454/CustomPlayerModels#201]
As the title says.
Models will not load client side if a server is in offline mode.
Various work arounds have been tried, including installing the CPM plugin.

Two things to note however is that if the model is loaded through the Models tab, it WILL show for other CPM client users. This also works with the command /cpm setskin command.
again, other people can see your model but you yourself cannot.

Shown here are other player models loaded. But as seen here, mine isn't seen on my own end.
 
 
![2022-03-29_06 25 05](https://user-images.githubusercontent.com/56050751/160643850-6e6e383f-818b-48d5-9115-68330f7fdc13.png)

Other players have this same issue.

As seen above, the skin is "loaded" but not showing, except in the case where menus/plugins use the player head as an icon/button where it does render: 

![image](https://user-images.githubusercontent.com/56050751/160644434-4073be5a-9732-4573-852f-9761088a3851.png)

One other thing is the possibility of CPM conflicting with Skinrestorer,

But so far have proved inconclusive

**Comment by tom5454** [comment]
Most likely a bug/incompatibility with Skinrestorer, use the models system for offline servers.
