### ISSUE TITLE
Bug: Game Crashes when a Parrot sits on your shoulder

### ISSUE THREAD

**Issue by FyrfyX8** [tom5454/CustomPlayerModels#206]
My game Crasges when a parrot sitson my shoulder

here is the log:
[2022-04-09-7.log.gz](https://github.com/tom5454/CustomPlayerModels/files/8456809/2022-04-09-7.log.gz)

**Comment by tom5454** [comment]
This looks like an issue with Optifine, but I couldn't reproduce it with Optifine H7.
