### ISSUE TITLE
(Fabric) Glowing eyes layer's stop rendering and need a skin update to show up again

### ISSUE THREAD

**Issue by netcore10** [tom5454/CustomPlayerModels#210]
(Fabric 1.18.2)
Glowing eyes works on "Test in game" but when you save and upload, sometimes the layers don't get rendered when you join a world or server.

Exporting and updating fixes it until you relaunch the world or minecraft.

**Comment by tom5454** [comment]
Do you have Optifine or Sodium?

**Comment by netcore10** [comment]
No, it was doing it without shader's or sodium.

**Comment by netcore10** [comment]
> No, it was doing it without shader's or sodium. (made sure to test CPM on it's own. it took a client restart for it to register again, but did it again if you edit the model or open the menu, the glow layers disappeared, until client restarted, )

or if i exported again, to skin
