### ISSUE TITLE
Crash with reborn core 5.2.0-beta3 (Fabric)

### ISSUE THREAD

**Issue by netcore10** [tom5454/CustomPlayerModels#211]
[crash-2022-04-21_01.17.58-client.txt](https://github.com/tom5454/CustomPlayerModels/files/8526241/crash-2022-04-21_01.17.58-client.txt)

**Comment by netcore10** [comment]
also happens with the tech reborn update

**Comment by netcore10** [comment]
Also happens with the latest jamtastic update.

**Comment by tom5454** [comment]
Can you post your full log

**Comment by netcore10** [comment]
This issue has been solved on most of their parts.
