### ISSUE TITLE
Informed GUI is too Large for the Model Editor to Work while GUI is set to size 2

### ISSUE THREAD

**Issue by aacarangan** [tom5454/CustomPlayerModels#213]
So I frequently have my GUI set to either 1 or 2 because I don't like the large sizes. I don't change this ever really. I usually do not have this problem when using the editor yet this just popped out of no where. I restarted the game, restarted my launcher, restarted my computer, changed my GUI size to see if it'll line up and just fix itself but it's a no go.
![Screenshot_20220424_084901](https://user-images.githubusercontent.com/94731751/164984933-e72eba7b-7c7d-465e-a796-aeb2bbffefb5.png)
![Screenshot_20220424_084941](https://user-images.githubusercontent.com/94731751/164984937-0851e91d-75dd-4939-af51-32ad4c2aeacd.png)
![Screenshot_20220424_084958](https://user-images.githubusercontent.com/94731751/164984942-7462e406-4b72-4395-961c-2cd15f4675a1.png)

**Comment by tom5454** [comment]
Go to Edit/Settings then under the Editor tab change the scale there.
