### ISSUE TITLE
Hand Model Doesn't Render Correctly [Fabric 1.17.1]

### ISSUE THREAD

**Issue by Minemaker0430** [tom5454/CustomPlayerModels#216]
In previous versions that I've used (Forge 1.16), the Hand Model that's rendered in first person always renders from the Right/Left Arm Model, however in this version the Hand doesn't match up with the Arm Model and the texture breaks completely if you have a texture sheet bigger or smaller than the Vanilla default of 64x64

What it should look like:
![2022-05-07_13 08 06](https://user-images.githubusercontent.com/85040155/167268505-c3591352-846e-4c53-9dd9-647f8860ddc4.png)

What it actually looks like:
![2022-05-07_13 08 17](https://user-images.githubusercontent.com/85040155/167268521-c0f08efa-4a5b-4e93-b734-5abea341d5aa.png)

Keep in mind both the vanilla and custom Right Arm Models look the same.

Edit: Another thing I should mention is that I used the convert Vanilla parts tool after writing this and the same thing happened again.

**Comment by tom5454** [comment]
What other mods do you have installed?

**Comment by Minemaker0430** [comment]
- Slight GUI Modifications
- Animatica
- Architectury API
- ARRP
- BetterF3
- CIT Resewn
- Clear Despawn
- Clear Skies
- Cloth API
- Cloth Config API
- Colormatic
- Continuity
- Cursor Mod
- Custom Entity Models
- Custom Splash Screen
- Entity Texture Features
- Fabric API
- Indium
- Iris Shaders
- LambdaBetterGrass
- LambDynamicLights
- Lithium
- Mod Menu
- Not Enough Crashes
- Ok Zoomer
- Phosphor
- Replay Mod
- Sodium

**Comment by Minemaker0430** [comment]
Yep, it worked

**Comment by Minemaker0430** [comment]
I tested it some more and it seems to be an issue with Entity Texture Features specifically

**Comment by pessoacasual12** [comment]
> I tested it some more and it seems to be an issue with Entity Texture Features specifically

Because Entity Texture Features has a thing where you can add additional parts to your player only in the skin file.
