### ISSUE TITLE
What voice chat mods are supported?

### ISSUE THREAD

**Issue by DearFox** [tom5454/CustomPlayerModels#217]
I checked Plasmo Voice and nothing seems to be happening with it.
What mods are supported and how to use this feature? Can I have an example?

**Comment by tom5454** [comment]
There aren't any right now.
CPM has an API (in 0.4.0) for registering voice.
https://github.com/tom5454/CustomPlayerModels/wiki/API-documentation#voice-animation
Voice chat mods have to implement compatibility.
