### ISSUE TITLE
no server config file in the new fabric 1.18 0.4.0a update

### ISSUE THREAD

**Issue by Dizvx** [tom5454/CustomPlayerModels#219]
just updated the mod on my server and there is no config file for cpm 1.18 0.4.0a
i've tried restarting my server, reinstalling the mod, and looking in the mod files and there was never a server config file given/shown?
![Screenshot 2022-05-14 210319](https://user-images.githubusercontent.com/69993102/168452984-84ece297-b0f7-4568-892c-68301892d9a0.png)
![image](https://user-images.githubusercontent.com/69993102/168452990-4b199075-3f3e-4fa7-9064-b99adf3e6cbd.png)
![image](https://user-images.githubusercontent.com/69993102/168452993-7f279c8b-9685-4089-baed-822f1fd6bb6b.png)

**Comment by thenumbertwo1** [comment]
i really fucking hope this is shitternos's fault

**Comment by tom5454** [comment]
the server config is in world/data

The new 0.4.0a default config only works when you create a new world.
