### ISSUE TITLE
Skin Model does not update when updated through Skin Swapper unless you restart game

### ISSUE THREAD

**Issue by Lucipo** [tom5454/CustomPlayerModels#23]
latest version as of Feb 25th, 2021, fabric

Pretty much the title, you can upload and everything works but you have to restart game for it to change client-side, when it was instant without this mod.

**Comment by tom5454** [comment]
For the skin change to take effect you have to exit to the title screen and wait 15 seconds for the cache to clear. You can't change skins while in the world.

**Comment by Lucipo** [comment]
Nah I mean with this mod:
https://www.curseforge.com/minecraft/mc-mods/skin-swapper 

The changes apply to the MC account, namemc, and vanilla, but the skin you launch the client with still persists with the attached model. Without custom player models installed, it is instant for the client and all other players on all platforms.

**Comment by tom5454** [comment]
Custom Player Models has a cache that clears after 15 seconds of the model not showing, then it should re-download everything.

**Comment by Lucipo** [comment]
> 
> 
> Custom Player Models has a cache that clears after 15 seconds of the model not showing, then it should re-download everything.

Can you try to reproduce it and use the mod in fabric and change skin with skin swapper from a vanilla skin to model skin and visa versa?

**Comment by tom5454** [comment]
I loaded up your modpack with a debugger, and when I join the world it downloads the skin, and loads the model. Minecraft is storing the skin url and doesn't refresh it after the skin change.

**Comment by Lucipo** [comment]
No I mean drag and drop any skin file (including one with model attached) into the skins folder of the pack, go to multiplayer tab on the title screen, top right (iirc) and change skin to anything but the one you loaded in with and it wont work until you restart the game. Im talking about that mod (skin swapper) lol

**Comment by Lucipo** [comment]
So is the compatibility issue fixable? The people on our server kind of cant restart all of our games everytime we want to show off a model or different skin

**Comment by tom5454** [comment]
I tested your modpack without custom player models installed and the skin-swapper mod doesn't work at all.
Minecraft stores the skin url. The skin change will show up for other players on a server if you relog, but your own skin is handled differenty. It is loaded the first time you join a world, and there is no way to unload it in vanilla.  (cobrasrock/Skin-Swapper#8) Skin swapper has to clear this cache when swapping the skin.

**Comment by Lucipo** [comment]
Ok thanks a lot for looking into it for me and sorry for the troubles
