### ISSUE TITLE
Animation position is not displayed correctly or the editor screen is displayed incorrectly when set position move far away.

### ISSUE THREAD

**Issue by AshiraLOL** [tom5454/CustomPlayerModels#231]
editor or in game animation displayed incorrectly.  idk

happened when animation set position move far away from base position.

only part has been set scale and stay in near base model still render far away.

(set position 400 look like 40)
https://user-images.githubusercontent.com/51751845/171903494-2cb6c29e-9482-40f5-a30e-7c54399fab02.mp4

**Comment by AshiraLOL** [comment]
set model scale size There is no problem because the part is stretched and position still in model limit zone.
https://user-images.githubusercontent.com/51751845/171906073-8207a53e-831f-4176-a6cc-b571a21355a7.mp4

**Comment by tom5454** [comment]
There is a limit of 48 on position values when exporting.
