### ISSUE TITLE
Additive animation bug

### ISSUE THREAD

**Issue by Azzarg** [tom5454/CustomPlayerModels#233]
Forge 1.18.2 latest mod version.

Sometimes opening the edior will cause all animations on the opened model to behave as if they were converted to additive, breaking everything. It affects the model after opening, even if the model was previously uncorrupted. The only fix I have found so far is reverting to a previous version of the model.
I am unsure how to replacate this, it seems to happen randomly, but very frequently.

**Comment by tom5454** [comment]
Can you send me a corrupted model? And did you test 0.4.2a update, it fixes a bug with animations not saving correctly.
