### ISSUE TITLE
Model Animations Breaking

### ISSUE THREAD

**Issue by Owen32123** [tom5454/CustomPlayerModels#235]
I've been working on a model for a while on the old version, before realizing there was an update, and updating it. But now some of my models are missing animations, and some of them are just messed up, with parts, like the head especially, just having all their movements removed. But, the biggest problem is that I was going through and fixing it, saved, and then when I reloaded it later, different parts were then messed up (For example, one pose was completely fine, and now all the parts have reset their movements.)
For example, a sleep position that's supposed to look like this
![image](https://user-images.githubusercontent.com/106932927/172071837-fd81b5aa-72ac-4a44-abdd-15926ba2abbe.png)
Now on the main version of the model looks like this 
![image](https://user-images.githubusercontent.com/106932927/172071900-03d0f0da-e2b0-4abc-9a1f-ae73c6a21ef7.png)
And it wasn't like that when I last saved the main version

**Comment by Owen32123** [comment]
The hunter model, and other versions of this model, were all created from the slugcat model, and the slugcat has all the animations that the other versions have, but they're all broken after saving

**Comment by tom5454** [comment]
0.4.1a had an animation breaking bug, models saved on that version didn't save the vanilla/root part animations. It was fixed in 0.4.2a.

**Comment by Owen32123** [comment]
I updated it to 0.4.2a. It didn't show me that the mod was updated again on curse forge

**Comment by Owen32123** [comment]
Correction: when updating to 0.4.2a it says to update it, and when updating, it switches back to the older version
