### ISSUE TITLE
[Suggestion] Color Picker tool that lets you save a color and reuse

### ISSUE THREAD

**Issue by Lucipo** [tom5454/CustomPlayerModels#24]
Where: Bottom Left under the skin texture png under Model tab

Function: Save any color that you save to just simply click the color to set the selected model block to that color, compatible with undo and redo buttons. Another super-useful option would be the ability to save any color from the applied skin file, in case you want to make a model that adds-on to a skin without opening it in a separate image editor program, color picking on it, copying the hex code and pasting it over (not having two monitors makes this even more of a pain)

**Comment by TrialDragon** [comment]
For the color from skin file just ctrl left click the pixel in the texture tab. Though I agree, color picker in model menu would be nice.
[Wiki page on it](https://github.com/tom5454/CustomPlayerModels/wiki/Controls#editor-controls#image-editor)

**Comment by Lucipo** [comment]
I mean like, if I were adding a new cube in Modeling, the skin is on the bottom left, being able to ctrl-click a pixel on that little image of my skin and turn the selected cube into that color would save a lot of time in some scenarios.
