### ISSUE TITLE
1.7.10 More Player Models render issue

### ISSUE THREAD

**Issue by samasiassa** [tom5454/CustomPlayerModels#242]
Render issues on 1.7.10 version with More Player Models installed appears while looking at CPM model.

Full log: https://paste.ee/p/zDsU3

Render error log part:

> [18:28:46] [Client thread/ERROR]: Couldn't render entity
> java.lang.ClassCastException: com.tom.cpm.client.PlayerRenderManager$RedirectModelRenderer cannot be cast to noppes.mpm.client.model.ModelScaleRenderer
> 	at noppes.mpm.client.model.ModelMPM.renderHead(ModelMPM.java:284) ~[ModelMPM.class:?]
> 	at noppes.mpm.client.model.ModelMPM.func_78088_a(ModelMPM.java:170) ~[ModelMPM.class:?]
> 	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_77036_a(RendererLivingEntity.java:290) ~[boh.class:?]
> 	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:149) [boh.class:?]
> 	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:158) [bop.class:?]
> 	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521) [bop.class:?]
> 	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293) [bnn.class:?]
> 	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271) [bnn.class:?]
> 	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244) [bnn.class:?]
> 	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:471) [bma.class:?]
> 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224) [blt.class:?]
> 	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015) [blt.class:?]
> 	at noppes.mpm.client.EntityRendererAlt.func_78480_b(EntityRendererAlt.java:34) [EntityRendererAlt.class:?]
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by tom5454** [comment]
This is an issue with More Player Models. I can't fix it.
