### ISSUE TITLE
Rendering issues with Iris

### ISSUE THREAD

**Issue by hackercat27** [tom5454/CustomPlayerModels#245]
In version 0.4.3a while running Iris, parts with the "Glowing Eyes" effect enabled will not correctly render. Sometimes these cubes will render underneath all cubes, but sometimes they will correctly render in front of the cubes. However, the glowing cubes don't use additive blending, and they appear similar to normal cubes.

Rendering behind:
![2022-07-09_23 33 54](https://user-images.githubusercontent.com/82016969/178130223-c6dddc12-41e3-4e0c-910e-4a5c3af82caa.png)

Rendering in front:
![2022-07-09_23 34 54](https://user-images.githubusercontent.com/82016969/178130222-ae94e0d7-bcfc-4b9a-8f28-4caeb34b150e.png)

Expected behaviour (Iris disabled):
![2022-07-09_23 40 14](https://user-images.githubusercontent.com/82016969/178130317-c6034e2c-a4c3-411b-94e1-d89f5ddee5be.png)

Additionally, the gizmos and cube outlines will always render behind the model in the editing window. Unlike in game, I haven't experienced them rendering in front of the model.

Current behaviour:
![2022-07-09_23 45 19](https://user-images.githubusercontent.com/82016969/178130415-4050a8fd-f62a-407a-9213-8294ed5a3498.png)

Expected behaviour (Iris disabled):
![2022-07-09_23 42 49](https://user-images.githubusercontent.com/82016969/178130366-74215851-7937-434b-8167-7a09041c8b27.png)

The issues are clearly a problem with specifically Iris. I ran Minecraft with only CPM, Sodium (which is required for Iris to function), and the fabric API, and the issue arises. When Iris is removed, the issue disappears.

**Comment by PelagicFox** [comment]
Same issue is happening for me too, though instead with ImmediatelyFast. This doesn't happen with ImmediatelyFast on my 1.20.4 version.

It seems the issue disappears in one of two situations:
1. Disabling ImmediatelyFast
2. Enabling "debug_only_and_not_recommended_disable_universal_batching" in ImmediatelyFast's configuration file.

1.21.7 Fabric (Prism Launcher).
