### ISSUE TITLE
Crashes When Loaded 

### ISSUE THREAD

**Issue by catboyminecraft** [tom5454/CustomPlayerModels#247]
I think I have the right Forge version, it just won't work for some reason. Maybe I just haven't found the pre-existing issue on here yet, but here's the crash log.

[crash-2022-07-14_20.25.29-fml.txt](https://github.com/tom5454/CustomPlayerModels/files/9116748/crash-2022-07-14_20.25.29-fml.txt)

**Comment by tom5454** [comment]
Forge 1.19 made breaking changes in forge version `41.0.64` you have to use `41.0.63`, for now. This will be fixed in the next update.
