### ISSUE TITLE
[Suggestion] Option to move skin editor tab from title screen elsewhere

### ISSUE THREAD

**Issue by Lucipo** [tom5454/CustomPlayerModels#25]
A few preset options specified in a config file would be best, an idea for it is to list presets and the user can change it at will.

Places like title screen (regular), options, and under skin customization ONLY (best)
Those would all be viable options

Personally I want the button to be hidden from regular users because I have some people on the server and modpack who have never used mods and clicking that as you launch the game can be overwhelming and give a bad taste in some people. I also have mods that remove fabric branding and mod count so it looks as vanilla as possible, this icon is the last thing that remains. Many thanks and much appreciated.

**Comment by tom5454** [comment]
You can hide the title screen button in cpm.json config file.
