### ISSUE TITLE
1.18.2 Crash on sleeping in bed, pose stack not empty

### ISSUE THREAD

**Issue by Starr12** [tom5454/CustomPlayerModels#251]
I tried adding Custom Player Models to "Better MC Forge 1.18" mod pack and the game crashes when attempting to sleep in a bed.

This was in a single player world, using the vanilla player model, I had not switched to a custom model yet.

The problem does not persist after disabling Customizable player models. And does not persist in an instance that has only the same version of CPM installed.

[crash-2022-07-22_10.59.23-client.txt](https://github.com/tom5454/CustomPlayerModels/files/9169356/crash-2022-07-22_10.59.23-client.txt)

**Comment by tom5454** [comment]
Duplicate of #289
