### ISSUE TITLE
editor menu doesn't fit screen

### ISSUE THREAD

**Issue by OrdinaryCloverOC** [tom5454/CustomPlayerModels#265]
when i open the skin editor the entire thing is too big to fit on minecraft. i am using 1.19 and i have other mods installed if you think that may be the problem. i can still use it like this but a few things are cut off. i can barely click some things at the top/bottom of the screen, although it is still entirely usable. CustomPlayerModels-Fabric-1.19-0.4.5a

**Comment by OrdinaryCloverOC** [comment]
the only mod MIGHT have incompatibility that i can think of is bedrockify as it changes the size of items, but that shouldn't effect menus.

**Comment by tom5454** [comment]
Change your gui scale in options, or under Edit/Settings/Editor

**Comment by OrdinaryCloverOC** [comment]
edit/settings/editor was hard to find due to the screen being so big but i used the options and it was fine
