### ISSUE TITLE
Crash on dedicated server

### ISSUE THREAD

**Issue by scmcgowen** [tom5454/CustomPlayerModels#266]
sometimes when a player joins, the dedicated server crashes

[crash-2022-08-10_20.48.37-server.txt](https://github.com/tom5454/CustomPlayerModels/files/9304147/crash-2022-08-10_20.48.37-server.txt)

**Comment by Jusey1** [comment]
Can confirm, same crash and this is Minecraft 1.18.2, Forge version 4.1.73 with mod version 0.4.7a.

**Comment by Jusey1** [comment]
After further investigation, we figured out that this crash has something to do with the player using a saved model file instead of uploading the model as a skin to their Minecraft account. (Which explains why I cannot crash my own server).

**Comment by pokycraftgamer9** [comment]
Update
On even further investigation it effects gits as well not just model files
When you attempt to change Models without any other players online it works just fine but if a player comes online and your using a cpm model the server crashes, if you have it on reset skin sometimes they may see a cpm model you have or your hitbox will still be the size of one of your cpm models
it effects ALL types of models.

**Comment by Jusey1** [comment]
Poky also tested a bit more and I am going to add that these crashes started in 0.4.6a, so downgrading down to 0.4.5a will fix the issues. So whatever was changed in 0.4.6a broke the mod for some players (it doesn't effect all players).
