### ISSUE TITLE
Armor from PSI mod is not hidden

### ISSUE THREAD

**Issue by Re-e-e** [tom5454/CustomPlayerModels#267]
The armor from the PSI mod, made as a model and not the usual texture, does not react to the settings of the armor elements in the editor (does not hide, does not move, does not rotate, nothing)

All armor is hidden
![image](https://user-images.githubusercontent.com/111039720/184072614-f991045e-e5cd-4984-8cff-b5313b68fdcf.png)

But not the armor from this mod (and it looks terrible on some models)
![image](https://user-images.githubusercontent.com/111039720/184072978-0d58f1f4-0816-4a8c-b95a-2aa194250a61.png)
![image](https://user-images.githubusercontent.com/111039720/184072991-7501b0b8-fe6c-4e17-98fb-ca490507f337.png)

**Comment by tom5454** [comment]
You have to use something like https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked and hide the armor. CPM can't edit modded armor with custom models.
