### ISSUE TITLE
CPM model exporting gone horribly wrong.

### ISSUE THREAD

**Issue by Cataraxts** [tom5454/CustomPlayerModels#269]
![image](https://user-images.githubusercontent.com/83794920/184414199-6d443f5a-cd5b-48f6-bd54-7d8ed996304a.png)

Okay so this is my current dilemma. I suspect it has something to do with a cube size limit on CPM, been looking through the code to find a way to remove this limit to no avail. Please fix.
[playermodelnedlehaver.zip](https://github.com/tom5454/CustomPlayerModels/files/9328902/playermodelnedlehaver.zip)

Here are both the cpmproject and the cpmmodel. Tested on 1.18.2 forge and 1.19 fabric with the same results.

**Comment by tom5454** [comment]
CPM has a limit of 25 on cube sizes. You have to split up the cubes in Blockbench.
