### ISSUE TITLE
[Suggestion] Ability to copy entire parts/cube amalgomations from one part to another

### ISSUE THREAD

**Issue by Lucipo** [tom5454/CustomPlayerModels#27]
Skins are usually symmetrical, would save a shit load of time (like saving one arm to the other side and editing what needs to be changed instead of building the same model from scratch)

and if there is already a way then just yeah close and respond

(a discord to ask questions in a channel rather than open issues would be so much better)

**Comment by tom5454** [comment]
I made a discord server: https://discord.gg/mKyXdEsMZD
