### ISSUE TITLE
Models not loading on LAN

### ISSUE THREAD

**Issue by BlindTwig** [tom5454/CustomPlayerModels#270]
Custom models refuse to load on LAN servers, and it's in several odd ways. Sometimes, they load fine, sometimes they require a death to work, and sometimes they'll work only for the person hosting the LAN server and nobody else. This does not occur at all on dedicated servers, however if somebody hosts one on the same PC that they're playing on, they will no longer be able to see their own model, however everything else works perfectly.

I'm sorry that this is a bit of a messy bug report, I haven't submitted one for anything in a while and I didn't see any format already used here before. If I need to provide logs or recordings to help figure out what's happening please let me know and I'll gladly do so.

**Comment by tom5454** [comment]
What version of minecraft are you using? Are you using the latest CPM Release? Check the Error Log under the `Gesture Menu (G)` / `Social Settings`/`Error Log`, if there is an issue with model loading it should show up there. Please post both of your logs (after this issue happens).

**Comment by BlindTwig** [comment]
We were using 1.18.2, latest CPM release, and unfortunately I did not grab the logs from that exact menu at the time of it happening. Are they still stored somewhere I can get them now or will I have to try and replicate the issue and get a new log?

**Comment by tom5454** [comment]
Post your minecraft log, it may have some info, but you have to replicate the issue to see it in the `Error Log` menu.

**Comment by tom5454** [comment]
Try the latest version (0.4.8a) model loading had issues on 1.17+
