### ISSUE TITLE
Won't let me change scaling settings 1.19

### ISSUE THREAD

**Issue by aconeishone** [tom5454/CustomPlayerModels#271]
I have the custom player mod and pekhui mod both in the mods folder, both mods are loaded in-game. For some reason, it will not let me change things like adjusting eye height and such, no clue why this is

**Comment by tom5454** [comment]
Update CPM. Pehkui support was added to 1.19 forge in 0.4.4a.

**Comment by aconeishone** [comment]
> Update CPM. Pehkui support was added to 1.19 forge in 0.4.4a.

k ty, can you give me a link for which version to use? It's ok if no

**Comment by aconeishone** [comment]
wait nvm I found it tysm
