### ISSUE TITLE
CPM model not appearing in latest versions

### ISSUE THREAD

**Issue by Pantheris2019** [tom5454/CustomPlayerModels#272]
CPM in latest versions when click test ingame, CPM does not load the model and nobody else can see the model either.,

**Comment by tom5454** [comment]
Try the latest version (0.4.8a) model loading had issues on 1.17+

**Comment by Pantheris2019** [comment]
Alright thanks, my friends and I will try it as soon as the update is pushed to curseforge client.  Thanks for the quick response!  We will get back to you as soon as we know anything!
