### ISSUE TITLE
Crashing with Physics Mod cloth physics

### ISSUE THREAD

**Issue by Marsephel** [tom5454/CustomPlayerModels#274]
Game crashes when using CPM models and Physics Mod with cloth physics for cape turned on. 
![crash](https://user-images.githubusercontent.com/111594291/185673248-97f8ea57-2e23-45b7-aa56-82b23caa8fb0.png)
[latest.log](https://github.com/tom5454/CustomPlayerModels/files/9384142/latest.log)

**Comment by tom5454** [comment]
Was fixed by Physics Mod in haubna/PhysicsMod#435
