### ISSUE TITLE
Model parts with the "Glowing Eyes" attribute doesn't show up correctly on other clients.

### ISSUE THREAD

**Issue by Yosomii** [tom5454/CustomPlayerModels#278]
Without the attribute they show up properly, however with, the "glowing eyes" I attached to the head model show up at their feet.
This only shows on other clients. :(

Version 1.19.2
CustomPlayerModels-1.19-0.4.8a.jar
Playing on an LAN server
![2022-08-27_17 06 17](https://user-images.githubusercontent.com/91393711/187052123-742afa5d-e1b3-45e0-9461-a70baa0540a8.png)
![2022-08-27_17 06 39](https://user-images.githubusercontent.com/91393711/187052145-28ad9ff1-35fe-4873-9ba7-246bfd6769e1.png)
.
Link to model: https://drive.google.com/file/d/1vnwH4KSOAd3wuba3fMAyppNc9CjRHVQp/view?usp=sharing

**Comment by tom5454** [comment]
Do you have optifine?

**Comment by Yosomii** [comment]
yeah, is that what's causing the issue?
