### ISSUE TITLE
Slider Bugs (value gestures)

### ISSUE THREAD

**Issue by The-Weeb-Guy** [tom5454/CustomPlayerModels#280]
There are a few issues with the sliders added in 5.0
1.) They do not respect the Hidden By Default Effect
2) It appears that only 2 sliders can be fully functional at a time
I have videos for both bugs.
Hidden By Default Bug Video
https://user-images.githubusercontent.com/59518595/187558771-eb3f0ab3-7302-4dcb-9e06-708a094f15d9.mp4

https://user-images.githubusercontent.com/59518595/187558774-c4469abe-afa4-45d0-b3ac-11ade1bfe527.mp4
Slider Limit Bug Video
https://user-images.githubusercontent.com/59518595/187558830-ae142101-7f4a-4224-a08b-a5f7b4acf1df.mp4

**Comment by The-Weeb-Guy** [comment]
Upon further study its not that there's only 2 sliders but maybe 1 just doesn't work ingame.
https://user-images.githubusercontent.com/59518595/187562573-b7086f41-ba08-41a8-adb6-5726459a8c8a.mp4

**Comment by tom5454** [comment]
Can you send me the projects?
Also check the interpolation on the green slider on the third video, it looks like you left it on a looping variant.

**Comment by The-Weeb-Guy** [comment]
I would except opening all files where I get the bug today shows no symptoms of the issue. However I HAVE been able to replicate the issue and will drop the file I made in the replication video and the video itself.

https://user-images.githubusercontent.com/59518595/188241624-36cd5aa4-9382-4657-b48e-c68432d9c3d0.mp4
[adad.zip](https://github.com/tom5454/CustomPlayerModels/files/9481298/adad.zip)
(the .zip file is the file i made in the video replicating the issue but I replaced `.cpmproject` with `.zip`)
