### ISSUE TITLE
cpm setskin only display the change to nearby players

### ISSUE THREAD

**Issue by Doc94** [tom5454/CustomPlayerModels#282]
Not sure if is a issue but when use the command for test model if the other players are not close they not see the change of the model.

**Comment by tom5454** [comment]
What version are you using? What version is the server?

**Comment by Doc94** [comment]
> What version are you using? What version is the server?

Version: CustomPlayerModels-Fabric-1.17-0.5.0a
Server: Minecraft 1.17.1 with Fabric Loader 0.13.3

Attach a gif show how i set a model to a player not close to me and teleport to him to see nothing change, if run the command with the target close then work.
