### ISSUE TITLE
One players model wont load regardless of my settings.

### ISSUE THREAD

**Issue by iAmInActions** [tom5454/CustomPlayerModels#283]
So, I recently played on a server with a few friends and we set up custom models and everyone had theirs load except for one player with the name clover_the_fox. Screenshots of all settings are attached.
![2022-09-01_19 42 32](https://user-images.githubusercontent.com/83808704/187979133-c2db524c-9d2d-43e0-820c-96f12dbedece.png)
![2022-09-01_19 42 59](https://user-images.githubusercontent.com/83808704/187979142-963ff9fa-02b2-448d-be21-3096bc6e2064.png)
![2022-09-01_19 43 03](https://user-images.githubusercontent.com/83808704/187979146-31f29056-af30-4129-af4c-e033a113d25c.png)
![2022-09-01_19 43 06](https://user-images.githubusercontent.com/83808704/187979194-6ad61ebc-1692-4db2-9056-73a1a8045dad.png)

**Comment by tom5454** [comment]
1. Update the mod
2. clover_the_fox doesn't exist on NameMC, priated versions of minecraft has issues loading models.

**Comment by iAmInActions** [comment]
> 2. clover_the_fox doesn't exist on NameMC, priated versions of minecraft has issues loading models.

he recently changed his name to CookieDaVali

**Comment by iAmInActions** [comment]
Still wont load with the updated mod though.
