### ISSUE TITLE
One users skin still wont load on the newest version

### ISSUE THREAD

**Issue by iAmInActions** [tom5454/CustomPlayerModels#288]
Hello,

I have had an issue here before that boiled down to being caused by a wontfix related to different auth servers and their effect on skin loading. The other users from that issue have since bought a legitimate copy of the game and are all signed in with the official latest version build of the mod and no other mods. However, one users model still wont load with the error "Model loading disabled by safety settings" but all safety settings are fully disabled for both the users and server.
![2022-09-10_20 03 59](https://user-images.githubusercontent.com/83808704/189496276-3da796fb-ed50-4b62-bec9-abad782d5d58.png)
Any help on this would be appreciated.

**Comment by tom5454** [comment]
Open the Error Log in Social Settings and see what's blocking the model loading. The model loads fine in the Web viewer ([https://tom5454.com/cpm_viewer.html?name=CookieDaAvali](https://tom5454.com/cpm_viewer.html?name=CookieDaAvali)), and as a player head in my game. Make sure your server is on `online-mode`.
