### ISSUE TITLE
Help with Exporting?

### ISSUE THREAD

**Issue by RealMelodyHope** [tom5454/CustomPlayerModels#29]
Not necessarily an issue, but I just want clarification on how to export models...
I made a model completely different to the normal player model, and when I try to load it in game, it only shows the regular player model.
I just want some clarification on exporting and using custom models.

**Comment by RealMelodyHope** [comment]
Maybe a video going through the motions would be helpful?  I've been trying for a while now...

**Comment by tom5454** [comment]
The wiki has an article on exporting: https://github.com/tom5454/CustomPlayerModels/wiki/Exporting

**Comment by RealMelodyHope** [comment]
I saw that and tried following it, but the model isn't showing up, and I don't know what I'm doing wrong...

**Comment by RealMelodyHope** [comment]
Hmm... I was looking at previous threads, and the model I have also has custom animations.  Might this be part of the same issue?

**Comment by RealMelodyHope** [comment]
(also off-topic but how do you do multiple limbs?  like... another project i just started is a centaur model, and i'm trying to get the arms and legs to move nicely but they're being strange with how they rotate... tried playing with offset and position...)

**Comment by RealMelodyHope** [comment]
Speaking of offset and position, it looks almost like they behave the same way?  I was fiddling with offset and position again, and it looked like I got the exact same results for both...
This is also a suggestion: If you hold an arrow key (ie. for frames in an animation) that it'll scroll faster?  I have to individually click every time, which has lead to me making a keybind for spam clicking...  (a lot of the other suggestions I had, like a color dropper, were already suggested... maybe a saved color palate as well?  So you could save certain colors?)

**Comment by RealMelodyHope** [comment]
Yeah, I think there's something weird going on with exporting stuff that has animations... just made a new one, didn't do any animations, and it worked fine.

**Comment by RealMelodyHope** [comment]
OH!  I think I got it to work now!  Just gotta click into the skin visibility panel (or whatever its name is) and press OK.

**Comment by tom5454** [comment]
The skin visibility panel 'should' pop up when you export a model with animations for the first time (currently it doesn't).

The position is the rotation point of the element, and effects children elements as well.
While the offset only effects the box.

Also how many animation frames are you making?
The animations are interpolated between two end points, you don't have to define them frame by frame.

Multipile limbs are not suppored currently, but may be in the future.
