### ISSUE TITLE
Held item position bug

### ISSUE THREAD

**Issue by Azzarg** [tom5454/CustomPlayerModels#290]
When I wear any armour, my held item position is set to the vanilla position, as if I had Steve length arms. This looks very broken on my Enderman model, with items being held at my elbow. Changing the held item position in the editor has no effect.
The problem persists on the latest version for CPM on 1.16.5 Forge, 1.18.2 Forge, 1.19.0 Forge, 1.18.2 Fabric, and 1.19.0 Fabric, regardless of mod list, reguardless of model used.
Strangely, using the Cosmetic Armor mod to hide my Armour fixes the issue. However, using CPM to make my armour hidden by default does not solve the problem, with my held item error persisting when I equip my now invisible armour.

**Comment by The-Ice-Lord** [comment]
I still have this issue in 1.20.1, but I don't even have a held item position in the editor.
