### ISSUE TITLE
1.19.2 Skin Editor gives some error when i want to open it

### ISSUE THREAD

**Issue by kirillstrizhak** [tom5454/CustomPlayerModels#293]
I can't open Skin Editor, when i press this button i **always** got this

![report](https://user-images.githubusercontent.com/107313077/191484392-8ba4cf68-1c29-454b-a44e-3304f4309541.png)

i'm using Minecraft version 1.19.2 with Forge version 43.1.16 and Optifine HD U_H9 for MC 1.19.2
**here is my full log**

[latest.log](https://github.com/tom5454/CustomPlayerModels/files/9615811/latest.log)

**Comment by tom5454** [comment]
Buy the game
