### ISSUE TITLE
fix the fact that clients don't receive the correct states for gestures when loading other player's models

### ISSUE THREAD

**Issue by chyzman** [tom5454/CustomPlayerModels#294]
when a client first renders another player's model the gestures/toggles/values/whatever dont get synced correctly until the player updates a gestures or reloads there model

**Comment by tom5454** [comment]
Are you on fabric?

**Comment by chyzman** [comment]
it happens on both tho possibly more so on fabric

**Comment by tom5454** [comment]
Can't reproduce on Forge, can on Fabric, Duplicate of #282
