### ISSUE TITLE
Bug with displaying a sleeping character on behalf of other players

### ISSUE THREAD

**Issue by Re-e-e** [tom5454/CustomPlayerModels#296]
When I go to sleep on a bed with a third-person view, I'm lying right on it, as intended, but other players see me hovering over the bed (screenshots from below).

What I see
![image](https://user-images.githubusercontent.com/111039720/193468665-d40738f1-7498-4004-bbc7-5e6bc239789e.png)

What others see
![image](https://user-images.githubusercontent.com/111039720/193468693-9cd1e29d-9d09-4c23-8f2e-003aa85040de.png)

Tested it on another model (cynadydes avali model), it has the same problem. Perhaps this is due to an incorrect translation of the position display of the scaled avatar, since all our models are smaller than usual.

**Comment by tom5454** [comment]
This is vanilla jank you can see this with a steve model in vanilla in 1.19.2
![Jank](https://user-images.githubusercontent.com/20185760/194776440-843d9a0a-f35c-4032-a191-b5f05e946f6c.png)
I may add a special case in CPM though.
