### ISSUE TITLE
Pluging Problem .cpmproject

### ISSUE THREAD

**Issue by KimiQ83** [tom5454/CustomPlayerModels#298]
Hi, I have a problem with the .cpmproject. I can't export the files. It marks a mistake in cube and in textures. I don't know if it's because of the blockbench update, in that case, which version is the right one to be able to run it?

----
Hola tengo un problema con el .cpmproject no puedo exportar los archivos me marca error en cube y en texturas. desconozco si es por la actualización de blockbench  en ser  ese caso cual vercion es la adecuada para poderlo ejecutar?

**Comment by tom5454** [comment]
Please send a screenshot of your error. You can only use one texture sheet for your model, and you have to stick to the CPM roots format, join the discord for more help with Blockbench issues (https://discord.gg/mKyXdEsMZD).

**Comment by KimiQ83** [comment]
Hi  this is what hapen 

![image](https://user-images.githubusercontent.com/115377156/194997873-478cee79-bb4c-434d-a422-8634ceb886e0.png)

**Comment by tom5454** [comment]
You can't have multiple textures for your model. CPM only supports a single texture per model.
