### ISSUE TITLE
Texture page doesnt allow me to choose a few options

### ISSUE THREAD

**Issue by Maxwellkc** [tom5454/CustomPlayerModels#3]
The texture page looks really strange, and yes i HAVE turned texture mode on with my singular cube.
![Screenshot 2021-02-05 183204](https://user-images.githubusercontent.com/78626647/107102579-882e4100-67e0-11eb-9b16-d47f975c7842.png)

**Comment by Maxwellkc** [comment]
I can't even lick on the, well, what I presume to be the load skin button. The color button doesn't work for me either.

**Comment by stachmann** [comment]
try minimizeing the window and changeing it to a diffrient size, not saying it is the fix, but it worked for me.

**Comment by Maxwellkc** [comment]
That doesn't seem to work.

**Comment by tom5454** [comment]
Changing your Gui Scale in options/Video Settings.
