### ISSUE TITLE
Model will not load in game

### ISSUE THREAD

**Issue by Nindota** [tom5454/CustomPlayerModels#30]
I've made and exported a model 6 times using the 1.17 and 1.16.5 Fabric versions, as well as the 1.16.5 Forge version, but all that loads in game is the vanilla skin. I've tried applying the skin both using Minecraft.net and the Minecraft launcher, with the same result on all versions of the game I tried it with.

The versions of Fabric I used are 0.11.1-1.16.5 and 0.11.2-21w07a
The version of Forge I used was Forge 36.0.43

All skins exported are located below, all using gist

![ModelSkin](https://user-images.githubusercontent.com/29005613/109437207-0b1a7400-79fa-11eb-9e57-4244f3da8e51.png)
![ModelSkin2](https://user-images.githubusercontent.com/29005613/109437209-0ce43780-79fa-11eb-9880-c4b7257dd0cd.png)
![ModelSkin3](https://user-images.githubusercontent.com/29005613/109437211-0e156480-79fa-11eb-9f14-421304e5339e.png)
![ModelSkin4](https://user-images.githubusercontent.com/29005613/109437214-0f469180-79fa-11eb-9d6f-ff37cbdfbe7f.png)
![ModelSkin5](https://user-images.githubusercontent.com/29005613/109437219-1372af00-79fa-11eb-9dd7-7856e6bf5bc6.png)
![ModelSkin6](https://user-images.githubusercontent.com/29005613/109437221-14a3dc00-79fa-11eb-9f9b-c677230fd578.png)

**Comment by tom5454** [comment]
Your model has 163 elements, the exporter currently breaks, if you have more than 128 elements. This bug will be fixed in the next release.

**Comment by Nindota** [comment]
Alright, thanks for clearing that up
