### ISSUE TITLE
Not showing the actual model

### ISSUE THREAD

**Issue by Psychodeus** [tom5454/CustomPlayerModels#305]
My hand size in Skin Editor and in-game are different, not showing the actual model.
![image](https://user-images.githubusercontent.com/93028949/198010484-f79581df-1216-4468-b101-71950e5dbeee.png)
![image](https://user-images.githubusercontent.com/93028949/198010587-5eac9f36-5ef8-4a0c-88c8-3a1f09e78d9c.png)

**Comment by tom5454** [comment]
Use `Edit/Tools/Convert vanilla parts`, or change your skin type in the minecraft launcher to default.
