### ISSUE TITLE
I can't play with cpm

### ISSUE THREAD

**Issue by THON1203** [tom5454/CustomPlayerModels#306]
Hi I have a very big list if mods and I can't play with cpm/CustomPlayerModels/CustomizedPlayerModel always when I add it the game loads up opens and then straight up crashes please help thanks

files: [the log download is here](https://github.com/tom5454/CustomPlayerModels/files/9870369/latest.log), [the modlist download is here](https://github.com/tom5454/CustomPlayerModels/files/9870440/modlist.log)

**Comment by tom5454** [comment]
You don't have cpm installed in your log file and there is no error message.
