### ISSUE TITLE
Loop buged?

### ISSUE THREAD

**Issue by Psychodeus** [tom5454/CustomPlayerModels#307]
![2022-10-28_08 33 07](https://user-images.githubusercontent.com/93028949/198422267-84141e35-891c-4a0b-8554-ed702ce533e1.png)

https://user-images.githubusercontent.com/93028949/198422733-b1e542da-665d-4aeb-8afc-45e072fa57aa.mp4

The loop isn't checked, but when I test it, it still looped.  I just want to make it linear.
Or do I set it wrong?

**Comment by Psychodeus** [comment]
And is there any way to just import only the animation part from other downloaded .cpmproject file? I there is, it would be so helpful!

**Comment by tom5454** [comment]
Use the setup and finish animations in `0.6.0a`, and no you can import animations from other projects.
