### ISSUE TITLE
Entire head glows when effect is applied

### ISSUE THREAD

**Issue by Lemonwaterie** [tom5454/CustomPlayerModels#311]
I followed a tutorial because i wanted to make my character's eyes glow, but instead, the whole head glows even though it's just the eyes on the layer. I'm so confused

**Comment by tom5454** [comment]
You probably enabled it on the head and not eyes. 
Please join the discord for support questions: https://discord.gg/mKyXdEsMZD
This site is for crash/bug reports and suggestions.
