### ISSUE TITLE
Models failed to load

### ISSUE THREAD

**Issue by Lalloyd7859** [tom5454/CustomPlayerModels#315]
Hi!
Im using your custom model for this mod, “++animations”, and ive encountered a problem which some skins work with the file great, but some the skin just doesn’t load or run the animation file.
After I click test ingame - my skin didnt load or the animation. It just says above my head - java.exeption.IO…. Model failed to load.
I dont know what could cause this - because the skins are just a png file.
And how come some skins works, and some doesn’t.
Could you help me figure this out?
Thanks!

**Comment by tom5454** [comment]
If you try test-in-game on a server, it won't work, you have to export the model. (Some smaller skins may work, but thats a side effect of the testing system)
Wiki page on Exporting: https://github.com/tom5454/CustomPlayerModels/wiki/Exporting
