### ISSUE TITLE
Unable to start game crashing on startup

### ISSUE THREAD

**Issue by imAuriss** [tom5454/CustomPlayerModels#318]
Im unsure of mod incompatibilities but would like help some help integrating this into my modpack.
[crash-2022-11-22_17.14.15-client.txt](https://github.com/tom5454/CustomPlayerModels/files/10071457/crash-2022-11-22_17.14.15-client.txt)

**Comment by tom5454** [comment]
It looks like `cosmetica` is conflicting with CPM.

**Comment by tom5454** [comment]
Duplicate of #261
