### ISSUE TITLE
Client render crash 1.19.2 (Replay mod mixin issue i think - also says animation)

### ISSUE THREAD

**Issue by netcore10** [tom5454/CustomPlayerModels#322]
https://mclo.gs/xosTmzv

**Comment by netcore10** [comment]
https://paste.atlauncher.com/view/9a551e2b-78d8-4fb4-9881-4496a5405716

**Comment by tom5454** [comment]
The first crash looks like some issue with Iris trying to optimize the game in a weird way make sure you are using the latest version of Iris (they had some crashing issues with some of the 1.4.x versions)

The last crash is from CPM, for some reason a player's model unloaded/appears unloaded in the middle of the animation handling code. Some code cleanups in the next version will fix this.
