### ISSUE TITLE
Animation priority doesn't always apply to [Hidden by default] or the [Visible] button in the animation frame editor

### ISSUE THREAD

**Issue by bfreezie** [tom5454/CustomPlayerModels#323]
I duplicated the player arms(including the held item) in order to have a set of arms that follows the player aim with the bow/crossbow, and then a set of arms that can do custom arm swing for the walking/running animation without holding the crossbow. The custom, non-additive walk animation is set to low priority with the appropriate arms toggled visible, and the non-additive crossbow holding animation is set to high with the appropriate arms set to visible.
Despite this, when I am holding the crossbow and start walking, the hidden arms of the low priority walk animation appear alongside the high priority arms of of the crossbow hold, and the crossbow item itself jumps back to the position of the walking animation.
![2022-12-07_17 26 57](https://user-images.githubusercontent.com/71112480/206337989-3ae42926-2dbd-47f6-84fe-4b1aecca31b2.png)
![2022-12-07_17 29 23](https://user-images.githubusercontent.com/71112480/206337992-dab02025-c3a7-47b8-8346-5c32d0de5ce1.png)
![2022-12-07_17 29 54](https://user-images.githubusercontent.com/71112480/206337994-f870fffa-4107-46e3-9c58-9b05a6b824df.png)
![holding crossbow](https://user-images.githubusercontent.com/71112480/206338023-106a4c29-a25f-48c1-9f45-4d5eb3b1d9c3.gif)
![walking](https://user-images.githubusercontent.com/71112480/206338026-d7fa9ac8-1ba2-4058-9a82-202d29f2ec64.gif)
![holding crossbow and walking](https://user-images.githubusercontent.com/71112480/206338028-49eb35f8-f3e0-4f27-91c9-149c45d3a50c.gif)

**Comment by tom5454** [comment]
It's a known issue similar to this (#280). Make a 0x0x0 sized cube that controls the visible/hidden effect, having animations moving parts can sometimes break the visibility.
This will be fixed when I clean up the project formats.

**Comment by bfreezie** [comment]
Thank you for the workaround
