### ISSUE TITLE
Held items bug [Fabric-1.19.3-0.6.1a]

### ISSUE THREAD

**Issue by bfreezie** [tom5454/CustomPlayerModels#326]
I just updated from Fabric-1.19-0.6.1a to Fabric-1.19.3-0.6.1a and I found that the held items on my model were all repositioned in game, but not in the editor view. I didn't see a held item change in the changelog, so I'm assuming it's a bug. Rolling back to the older version fixed the problem for now.
![2022-12-15_09 28 04](https://user-images.githubusercontent.com/71112480/207934113-55097a65-aff4-4006-9f7d-4b0f5128b2ac.png)
![2022-12-15_09 27 39](https://user-images.githubusercontent.com/71112480/207934155-9459d884-5a62-4560-a55c-001e60bba339.png)
![2022-12-15_09 42 36](https://user-images.githubusercontent.com/71112480/207934170-be017e75-fb38-475c-b613-65da3eb35c09.png)
And if you don't already hear it enough, you've made a wonderful mod. Thank you for all your hard work!

**Comment by tom5454** [comment]
Please send your mod list, I couldn't reproduce it with CPM only.

**Comment by bfreezie** [comment]
Cool, thanks!
