### ISSUE TITLE
Armor does not render properly in 1.19.3 / 0.6.1a

### ISSUE THREAD

**Issue by LogicalJoe** [tom5454/CustomPlayerModels#327]
Armor does not render correctly in `Minecraft 1.19.3 [Fabric Loader 0.14.11]` with `CPM 0.6.1a`, tested on a clean installation with `Fabric API 0.69.1+1.19.3`.
(model is _`Human_with_wings_public`_ by _`Kittybit#1848`_ on Discord)

<img width="301" alt="Screenshot 2022-12-15 at 15 16 59" src="https://user-images.githubusercontent.com/47825483/207958635-907dc312-c1c0-46d9-a925-e91323bc2d40.png">

<img width="392" alt="Screenshot 2022-12-15 at 15 17 53" src="https://user-images.githubusercontent.com/47825483/207958643-276655b3-d835-4990-9a45-3784a92ad8b0.png">

**Comment by TedAlter** [comment]
The same bug on 0.6.1a for 1.19.2 .
[Model for example.zip](https://github.com/tom5454/CustomPlayerModels/files/10254600/Model.for.example.zip)
