### ISSUE TITLE
Glow Issues in 1.18.2

### ISSUE THREAD

**Issue by Samwych** [tom5454/CustomPlayerModels#332]
I've been having an issue with glowing cubes in custom player models. Im currently running a variety of mods, but I'm not sure what could be the case. I've tried uninstalling Iris and other lighting mods but the issue still persists. The odd thing is that the glowing cubes still show up in the editing studio and in my personal inventory, but ingame (multiplayer and singleplayer) the glow does not appear. Examples below. First image is what my model looks like ingame, second images are in my inventory and model studio. My glow models used to work before, but over the past few days have stopped working. I do not know why! 

![image](https://user-images.githubusercontent.com/121124925/208736155-16be7da4-7c08-4caf-947e-1d793e56ab08.png)
![image](https://user-images.githubusercontent.com/121124925/208736212-66062619-9dbf-4bdf-a437-d9c8dcd28360.png)
![image](https://user-images.githubusercontent.com/121124925/208736289-b372921a-0bbe-4034-ad1e-a74bb98c72db.png)

**Comment by tom5454** [comment]
Try making the glowing cubes a little bit bigger using the MC Scale option (0.01 should work), it looks like it's rendering behind your model.
Please join the discord for support questions: https://discord.gg/mKyXdEsMZD
