### ISSUE TITLE
Editor model fails to load when testing in game

### ISSUE THREAD

**Issue by hackercat27** [tom5454/CustomPlayerModels#335]
In both singleplayer and multiplayer, if you press "test in game" in the editor, leave the editor, and then come back, the model will disappear. The only way to get the model back after entering the state (that I've found at least) is by completely reloading the editor (ie: leaving all the way back to the title screen and loading the model again)

**Comment by PurpleFuzzBall** [comment]
Was just about to write about this issue. This never happens in the older version of the mod.
I'm pretty sure this is a bug.

**Comment by PurpleFuzzBall** [comment]
@hackercat27 You can get around this by only testing from title screen then quitting out the world to the main menu.
