### ISSUE TITLE
Compatibility Crash with Supplementaries.

### ISSUE THREAD

**Issue by Jusey1** [tom5454/CustomPlayerModels#337]
MC: 1.19.2
Forge: 43.2.0
CPM: 0.6.2a
Supplementaries: 2.2.30
Moonlight: 2.1.21

Log: [Crash Log.txt](https://github.com/tom5454/CustomPlayerModels/files/10310875/Crash.Log.txt)

The crash happens when the player is in 3rd Person with a custom model and a Jukebox is ACTIVE.

**Comment by netcore10** [comment]
can confirm https://paste.atlauncher.com/view/222d4291-ef6c-4b26-9698-2332065e3bfd

**Comment by Jusey1** [comment]
Going to add to this, the mod author of supplementaries confirmed that the issue is happening because both this mod and theirs has a Mixin for ParrotShoulderLayer and this mod is causing theirs to return a pose stack when it is suppose to be empty, thus the crash happens. (Disabling the mixin on their end fixes the issue which is what I am doing temporally until this issue is fixed).

**Comment by xtriel** [comment]
> Going to add to this, the mod author of supplementaries confirmed that the issue is happening because both this mod and theirs has a Mixin for ParrotShoulderLayer and this mod is causing theirs to return a pose stack when it is suppose to be empty, thus the crash happens. (Disabling the mixin on their end fixes the issue which is what I am doing temporally until this issue is fixed).

was wonderin, how were u able to do this ? my friend tried but the crash didnt stop

**Comment by Jusey1** [comment]
> 

Open the mod with something like WinRAR then open the common-mixins file and remove the ParrotShoulderLayer (or something like that) from under client. It's directly above ParrotLayer.

**Comment by xtriel** [comment]
they're telling me that them doing that just causes minecraft to crash

**Comment by Jusey1** [comment]
It doesn't for me. Supplementaries runs just fine without that specific Mixin.
