### ISSUE TITLE
Still crash with CSL

### ISSUE THREAD

**Issue by Neubulae** [tom5454/CustomPlayerModels#34]
[crash-2021-03-07_16.06.07-client.txt](https://github.com/tom5454/CustomPlayerModels/files/6096798/crash-2021-03-07_16.06.07-client.txt)

**Comment by ZekerZhayard** [comment]
It seems that the higher the priority of Mixin, the earlier it will be injected, so the priority needs to be changed to less than 1000, not greater than. 
https://github.com/tom5454/CustomPlayerModels/blob/ea4afa2788b7a82e81928f9bbe1caf270651a18f/CustomPlayerModelsFabric-1.16/src/main/java/com/tom/cpm/mixin/PlayerRendererMixin.java#L25
