### ISSUE TITLE
Moving Objects Sometimes Skip Numbers

### ISSUE THREAD

**Issue by CheekyLobster** [tom5454/CustomPlayerModels#350]
I'm trying to precisely set an object at certain coords such as 0.9 and it skips to 0.89, and when I put 0.91 it stays 0.91. Happens with other numbers and parts randomly. Version is 1.16.5

![1](https://user-images.githubusercontent.com/122573269/212190099-11e06661-58e9-4320-b057-6ec8105a6de8.PNG)
![2](https://user-images.githubusercontent.com/122573269/212190103-8011f04b-f2d0-4b23-b7a2-725fc04f5997.PNG)

**Comment by tom5454** [comment]
Thats how computers handle floating point numbers, there is really nothing I can do about this.
