### ISSUE TITLE
Custom model doesn't import model correctly.

### ISSUE THREAD

**Issue by Goji54** [tom5454/CustomPlayerModels#354]
When I export the model into a .cpmproject file and import it into minecraft, it shows up as a steve model.

**Comment by tom5454** [comment]
Do you own minecraft, are you using skin or model export?
What version of Minecraft are you using?
Make sure you're using the latest version of the mod.

Please join the discord for support questions: https://discord.gg/mKyXdEsMZD
This site is for crash/bug reports and suggestions.
