### ISSUE TITLE
Per Face UV

### ISSUE THREAD

**Issue by WillowWhyTfIsThisTaken** [tom5454/CustomPlayerModels#357]
the plugin messes up the per face uv and everytime i load a model from blockbench in cpm i have to manually remake the UV which is really upsetting if u have 50+ cubes in your model

so could you please fix this?
overall i love the plugin :)

**Comment by tom5454** [comment]
What version of the plugin are you using? If you are using the old plugin try the new one https://github.com/tom5454/CustomPlayerModels/tree/master/Blockbench The plugin was rewritten recently.
If you're using the new one please send me your `.bbmodel`.

**Comment by WillowWhyTfIsThisTaken** [comment]
> What version of the plugin are you using? If you are using the old plugin try the new one https://github.com/tom5454/CustomPlayerModels/tree/master/Blockbench The plugin was rewritten recently. If you're using the new one please send me your `.bbmodel`.

i remade the model with the new plugin but i dont have access to my computer right now couls you please test it and send a screenshot?``

**Comment by WillowWhyTfIsThisTaken** [comment]
how do i attach files

**Comment by tom5454** [comment]
Put it into a `.zip` file
