### ISSUE TITLE
About the maximum number of animations.

### ISSUE THREAD

**Issue by AshiraLOL** [tom5454/CustomPlayerModels#358]
Did I reach the limit?

When I'm trying to update the old model, adding new Pose and Gesture, when I get to 117 animations, I can't save the file.
(must reduce to 116 to be able to save)

I tried fixing it in the "skin layer setting" menu, it still didn't help.

Is it a bug or normal?
I have too many animations?
The mod has a limit?

more info:
`CustomPlayerModels-Fabric-1.19.3-0.6.3a.jar`
`fabric-api-0.72.0+1.19.3.jar`

![2023-01-20_01 48 13](https://user-images.githubusercontent.com/51751845/213539920-d7b00329-931f-48a9-a97e-ccc8fd1dc187.png)
![2023-01-20_02 12 34](https://user-images.githubusercontent.com/51751845/213539930-4973e0db-472b-4324-9c28-7b94d8d5fb81.png)

So I'll have to focus on the model details instead for now...

**Comment by tom5454** [comment]
The mod has a limit of 61 (2^6-3) custom poses/gestures, due to the skin layers. A bug currently counts toggle and value layers into this (Which work differently, and has a limit of 253).
