### ISSUE TITLE
Error when exporting model

### ISSUE THREAD

**Issue by blueVena** [tom5454/CustomPlayerModels#361]
I get the same error when trying to export my project as a cpmproject. I'm using version 4.6.1 of blockbench, and 4.5.1 gets the same error.
![image](https://user-images.githubusercontent.com/123445839/214236922-1321e4ad-5789-412c-a5b9-a087d1178a9c.png)
![image](https://user-images.githubusercontent.com/123445839/214237367-3f0ca853-cd28-45ea-9ab9-be1432ecab03.png)

[phantom_v04_FINAL.zip](https://github.com/tom5454/CustomPlayerModels/files/10487354/phantom_v04_FINAL.zip)

**Comment by WillowWhyTfIsThisTaken** [comment]
rìght click on folder "root", select resolve folder and export it

**Comment by tom5454** [comment]
Resolve the root folder, and rename your textures. It should be `skin`, `armor1`, `armor2`, `elytra` (remove the `.png`)
