### ISSUE TITLE
Model import problem

### ISSUE THREAD

**Issue by KOTOKOPOlb** [tom5454/CustomPlayerModels#364]
When I import my model into Blockbench I get an error "Cannot read null properties (read 'b')" and the model doesn't load correctly.
[image](https://user-images.githubusercontent.com/82699565/214919196-e617a196-f818-433e-8a5c-d8ff1bd6c0ff.png)

**Comment by tom5454** [comment]
Please test the new version of the plugin.

**Comment by KOTOKOPOlb** [comment]
I uninstalled the old plugin and installed the new one, I get the same error

**Comment by tom5454** [comment]
Please send a screenshot of the DevTools console (Ctrl+Shift+I)

**Comment by KOTOKOPOlb** [comment]
![image](https://user-images.githubusercontent.com/82699565/215509270-ad0ef817-01b3-4b9b-9087-bfe762952c65.png)
