### ISSUE TITLE
Blockbench CPM Plugin won't export .cpmproject

### ISSUE THREAD

**Issue by LOTSASPAGHET** [tom5454/CustomPlayerModels#365]
![Export Error](https://user-images.githubusercontent.com/83330413/215379564-64e6ea43-61b3-4fe1-8a16-897963087d88.png)

**Comment by tom5454** [comment]
Please send a screenshot of the DevTools console (Ctrl+Shift+I)

**Comment by LOTSASPAGHET** [comment]
![Inspect](https://user-images.githubusercontent.com/83330413/215610259-820d0ef6-8941-4132-9e40-1c6b4d01e3d7.png)
