### ISSUE TITLE
`ICommonAPI.setPlayerModel()` not work

### ISSUE THREAD

**Issue by none283** [tom5454/CustomPlayerModels#378]
```Non-static method 'setPlayerModel(java.lang.Class<P>, P, com.tom.cpm.shared.io.ModelFile, boolean)' cannot be referenced from a static context```

when im trying to use `ICommonAPI.setPlayerModel(Player.class, playerObj, modelFile, forced);` method

**Comment by tom5454** [comment]
You need an instance of ICommonAPI to set the player model, and you must call this on the server! It won't work on the client.
