### ISSUE TITLE
Missing server-side mod, this feature is disabled!

### ISSUE THREAD

**Issue by ApoRaven** [tom5454/CustomPlayerModels#390]
im tryna use my custom animation but it doesnt work, pls help
![image](https://user-images.githubusercontent.com/44433530/224160595-36d02218-df3d-4979-8213-7e50ca6f7097.png)

**Comment by tom5454** [comment]
Your server doesn't have CPM installed.
You can use the Skin export mode, if you are playing on a vanilla server.
Please join the discord for support questions: https://discord.gg/mKyXdEsMZD
This site is for crash/bug reports and suggestions.
