### ISSUE TITLE
Crushed with notenoughIDs (1.7.10)

### ISSUE THREAD

**Issue by crafter0201** [tom5454/CustomPlayerModels#393]
I installed two mods below.
-CustomPlayerModels-1.7.10-0.6.5a
-notenoughIDs-1.7.10-1.4.6.

When loading game (Displayed loading screen), minecraft crashed.

↓Crash Report↓
[crash-2023-03-14_18.34.13-client.txt](https://github.com/tom5454/CustomPlayerModels/files/10969541/crash-2023-03-14_18.34.13-client.txt)

**Comment by tom5454** [comment]
Where did you get the notenoughids mod? Curseforge doesn't have that version.

**Comment by crafter0201** [comment]
Thank you for your prompt reply.

NotenoughIDs-1.7.10-1.4.6. downloaded from modpack (gt new horizons 2.3.0).
[https://www.technicpack.net/modpack/mcnewhorizons.677387](https://www.technicpack.net/modpack/mcnewhorizons.677387)
