### ISSUE TITLE
Glitchy skin when customizing a sleeping pose

### ISSUE THREAD

**Issue by WeneoBoi** [tom5454/CustomPlayerModels#394]
i don't know if it's just me or not but whenever i make a custom sleeping animation it makes the skin have a flashy effect, where the face of my character starts to change to a torso texture, overrall i can make custom sleeping animations but that one really makes me confused as of why it happens

to put it simply face texture turns into torso and back with camera movement after i test/play a custom sleeping animation
any ideas how to fix it?

**Comment by tom5454** [comment]
Please post your minecraft log, and screenshots of what's happening

**Comment by WeneoBoi** [comment]
Solved!
it seems it was the issue of the head part not being "Hidden by default" which in the end made the skin have the glitchy effect. all i had to do was check that box in the parts side, i probably somehow disabled it. Apologies for the inconvinience
