### ISSUE TITLE
Error with GUI

### ISSUE THREAD

**Issue by HeroRyker** [tom5454/CustomPlayerModels#396]
It says "Error drawing gui: java.lang.NullPointerException"

**Comment by tom5454** [comment]
Please post your minecraft log

**Comment by HeroRyker** [comment]
I deleted one mod and the error changed. Hold on.

**Comment by HeroRyker** [comment]
https://pastebin.com/MH2M0pQY

**Comment by HeroRyker** [comment]
I figured out what the problem is. It's the First Person Mod.
