### ISSUE TITLE
I think something is wrong with exporting texture, or my file is corrupted.

### ISSUE THREAD

**Issue by stachmann** [tom5454/CustomPlayerModels#4]
![Export](https://user-images.githubusercontent.com/78576022/107123607-709c9a00-686c-11eb-8490-571d920276c6.png)

On the Left is the model and texture i made, on the right is the exported texture on the model, i don't know why my texture looks like that when exported, my guess is that the .cpmproject file is corrupted and is stuck on a older version on the texture, but i don't know.

**Comment by tom5454** [comment]
The project file is a zip file look for a 'skin.png' file. If it's not in there try opening the texture on the left again with the open Skin button.

**Comment by stachmann** [comment]
The project file has the skin.png, but it is the texture on the left, and it still exports the one on the right, for some reason.
I deleted the skin.png file, but it created a copy of my skin that i am useing on my MC account.
so i changed my accounts skin to the unexported models skin, and then exported it, and it created the exported texture.

Then i changed my skin to the exported one and it dose not change the model, or am i doing it wrong?

**Comment by tom5454** [comment]
The project file should have the texture on the left. Your MC account shoudl have a texture that can load on vanilla Minecraft, like any normal minecraft skin. The mod writes data into the unused space on the vanilla skin texture. Then export it. And upload the exported texture as your skin.

I also released an update today maybe try with the new version as well.
