### ISSUE TITLE
Legs are offset from where they should be.

### ISSUE THREAD

**Issue by ShareYourHead** [tom5454/CustomPlayerModels#40]
The legs on the default model seem to be offset towards the back (positive z direction), and towards the center of the body going in the x direction. I don't know if this happens for the 4 pixel arms model (I would assume it does), but it does happen with the 3 pixel arms model. The translations on both the x and z axis seem to be to the same magnitude, but I'm not sure what the precise number would be to move it to the correct position (although it seems to be around 0.125 ish). I'm probably wrong, but my guess is that it has something to do with the rescaling of the player (because all entities are actually like... I think 0.85 the size that they would be if they were actually the same scale as blocks. I can't remember the exact number of the scale, but if it's important I know where to find it in the code)

**Comment by tom5454** [comment]
Can you post a screenshot, or a image explaining it? It doesn't look off for me.
