### ISSUE TITLE
(1.7.10)Skin doesn't display properly.

### ISSUE THREAD

**Issue by crafter0201** [tom5454/CustomPlayerModels#400]
Thank you for fixing bugs.
Thanks to you, I was able to play CustomPlayerModels with NotEnoughIds.

I installed only (CustomPlayerModels-1.7.10-0.6.6b). And forge version is (release 1.7.10-Forge10.13.4.1614-1.7.10).
In 1.7.10, Skin edited in-game (figure 1),skin doesn't display properly(figure 2,3).

The other versions were not problem. Specifically, 1.8.9(CustomPlayerModels-1.8-0.6.6b),1.19.4(CustomPlayerModels-1.19.4-0.6.6b).

![2023-03-26_23 47 30](https://user-images.githubusercontent.com/127858432/227784015-025500f0-f151-43ac-83c9-0913a71073d8.png)
figure 1

![2023-03-26_23 48 10](https://user-images.githubusercontent.com/127858432/227784172-4699bb8f-82de-4763-945c-8c04e25a0439.png)
figure 2

![2023-03-26_23 48 29](https://user-images.githubusercontent.com/127858432/227784184-5012c4b0-5d78-4234-9429-324853e50554.png)
figure 3

**Comment by tom5454** [comment]
You have to convert vanilla parts (Edit/Tools), 1.7.10 doesn't support 64x64 skins.

**Comment by crafter0201** [comment]
Thank you for your reply.

2023年3月27日(月) 0:48 tom5454 ***@***.***>:
