### ISSUE TITLE
Models not loading on Multiplayer world

### ISSUE THREAD

**Issue by NovaTheNeko** [tom5454/CustomPlayerModels#404]
I had started a new server with my friends but when we joined even with custom cpm files they only show loading above the head of our skins and not even actually loading in 3rd person despite loading the hand model correctly could i maybe get some help on what could be the problem

**Comment by NovaTheNeko** [comment]
the version of it is 1.12.2

**Comment by RedRain0o0** [comment]
This feels more like a problem for the [Discord](https://discord.gg/mKyXdEsMZ) than the GitHub Issues. Try asking in #mod-help

**Comment by tom5454** [comment]
Please post your minecraft log
