### ISSUE TITLE
Cannot disable vanilla head transform (position) without disabling vanilla head rotations.

### ISSUE THREAD

**Issue by nitronova** [tom5454/CustomPlayerModels#407]
The vanilla animations for heads in Minecraft allow for rotation that aligns with the camera in third person views. The vanilla animations for heads also displace said head for certain animation states, such as sneaking (even when in the air, water, on ladders, etc). Both of these animations are disabled at the same time when selecting Head and going to Effects > Disable Vanilla Animations.

Because both are disabled at the same time, you cannot fix the issues via disabling one without losing the other. If the vanilla head animation while sneaking displaces my head underwater and I want to fix it, disabling vanilla animations is the only way, and that's when I lose the ability to rotate the head with the camera in 3rd person view.

One proposed solution is to separate these vanilla animations for the head, somehow (perhaps by being able to re-enable vanilla rotations in animations). Another proposed solution is to include combined animation states, such as sneaking + falling, sneaking + water, sneaking + climbing. A third proposed solution is to be able to toggle non-additive transformations/rotations of specific model parts to frames of additive animations.

**Comment by tom5454** [comment]
You can use copy transforms to copy only the head rotation but not the position.
Please join the discord for support questions: https://discord.gg/mKyXdEsMZD
