### ISSUE TITLE
Occasionally face textures glitch and show entire skin for a moment

### ISSUE THREAD

**Issue by Pugo59867** [tom5454/CustomPlayerModels#408]
it's not noticeable until i look in f5 and i am not the only one who can see it, the video below shows what i mean

https://user-images.githubusercontent.com/131782673/234301065-2bf401cb-1259-4efe-ba6d-4675e9bc1a9b.mp4

**Comment by tom5454** [comment]
There is no video only sound.

**Comment by LoneDev6** [comment]
> There is no video only sound.

https://streamable.com/vy4qx5

**Comment by tom5454** [comment]
It may be an issue with the Essential mod, try it without it, or you have cubes under your model showing through, check it in the Editor.
