### ISSUE TITLE
The sleeve layers on slim models default to 3x12x3 instead of 3x12x4

### ISSUE THREAD

**Issue by Xigzagamer** [tom5454/CustomPlayerModels#41]
When I import a slim skin into the editor the sleeve layer doesn't display properly. I determined the cause being the editor defaults to 3x12x3 for sleeves instead of 3x12x4. This is very easy to fix, but will likely confuse new users who don't know the cause of the display issue.

**Comment by Oakstar519** [comment]
Also happens with the arms when you convert the vanilla parts to mod parts.

**Comment by Xigzagamer** [comment]
update, the bug appears to also affect the arms portion of the model in game. Unlike the sleeve layer this issue doesn't show up inside of the editor unless you first convert the vanilla parts.
