### ISSUE TITLE
Disabling Vanilla animations

### ISSUE THREAD

**Issue by WeneoBoi** [tom5454/CustomPlayerModels#412]
So, i've been messing around with custom walk and running animations and i'm asking if there's any way to disable them because i'd like to make a full on custom animations but due to them existing i can't seem to make them work properly

so am asking two questions:
1. Is this possible to implement?
2. is there a way to disable them from occuring?
Thanks for answering ^^
-Random CPM user

**Comment by RedRain0o0** [comment]
`Effects>Disable Vanilla Animations` should be what you're looking for!

**Comment by WeneoBoi** [comment]
that... existed???

holy sh- am so blind i didn't even realize it existed, thank you for the support! ^^
-Random CPM user
