### ISSUE TITLE
[Discord] Please, for the love of god, get some Discord Mods

### ISSUE THREAD

**Issue by RedRain0o0** [tom5454/CustomPlayerModels#418]
Your server is getting larger everyday, and you can't rely on Automod and CPMBot forever. So many people have been saying this in \#suggestions on the server, and even more have been saying that they'd volunteer. People love your server, and don't want to see it fall to trolls. At least consider.

**Comment by JadedChara** [comment]
I'd consider it myself, but my own practices are _absolutely not_ fit for providing assistance lol

**Comment by RedRain0o0** [comment]
Please Tom, there's so much growth due to QSMP. Kid's are flooding here due to the eggs and we need moderation.
