### ISSUE TITLE
Gui crash

### ISSUE THREAD

**Issue by RyanBark** [tom5454/CustomPlayerModels#424]
the guide says that it crashed and a code appears, does anyone know how to solve it?

![2023-05-30 (2)](https://github.com/tom5454/CustomPlayerModels/assets/135083679/3eb3a3a9-f3fd-4510-b8d9-7f67807f2bc2)

**Comment by firstdegreecam** [comment]
Not OP, but have the same issue. Tried with just the mod and api and with other mods. This is for version 1.20 though.

[crash-2023-06-09_21.41.53-client.txt](https://github.com/tom5454/CustomPlayerModels/files/11711347/crash-2023-06-09_21.41.53-client.txt)

[crash-2023-06-09_21.34.02-client.txt](https://github.com/tom5454/CustomPlayerModels/files/11711336/crash-2023-06-09_21.34.02-client.txt)

Had problems with the game crashing immediately in 1.19.4 with Optifabric installed as well, gives the ExitCode 1 without a crash log despite all mods being up to date.

**Comment by tom5454** [comment]
@firstdegreecam You are running an outdated version, the latest for 1.20 is `0.6.8a`

**Comment by firstdegreecam** [comment]
Sorry, posted the wrong crash logs. These are the right ones.
[crash-2023-06-10_14.42.27-client.txt](https://github.com/tom5454/CustomPlayerModels/files/11713179/crash-2023-06-10_14.42.27-client.txt)
[crash-2023-06-10_14.43.54-client.txt](https://github.com/tom5454/CustomPlayerModels/files/11713180/crash-2023-06-10_14.43.54-client.txt)

**Comment by firstdegreecam** [comment]
Thanks, sorry about that. It does in fact work. Was getting a lot of my mods mixed up trying to get things updated to 1.20.
