### ISSUE TITLE
[Blockbench plugin] Animations don't show up, duplicate or go skewey on blockbench

### ISSUE THREAD

**Issue by netcore10** [tom5454/CustomPlayerModels#425]
Sometimes when you export, animations duplicate - probably due to the fact it doesn't show pre-existing animations on the animation tab? When i import ones i made before (So i can edit them again) it usually struggles to find them in the editor when you "View in editor"

**Comment by tom5454** [comment]
Some animations will be split into a normal and a setup animation in CPM. Also Blockbench currently cannot import CPM animations, but it still keeps them in a hidden property.

**Comment by netcore10** [comment]
aaah that makes sense. So you can make them in blockbench, but they don't go back in when you save and reload.
