### ISSUE TITLE
[1.18] Copy Transform ROTATIONS don't work

### ISSUE THREAD

**Issue by joeyjake322** [tom5454/CustomPlayerModels#426]
I have hair blocks set to copy the X and Z rotations of the head, and the Y rotation set to 180 so that the hair always points downwards. This functions in 1.19 as intended, but loading the exact same model into 1.18 makes it no longer work. I also made a small test model in 1.18 and that again did not work.
![ig1 8](https://github.com/tom5454/CustomPlayerModels/assets/135862558/7380d941-7091-4c8d-b09b-33dc1782cc79)
![ig1 9](https://github.com/tom5454/CustomPlayerModels/assets/135862558/39e0125a-55c0-4c90-9549-051712571131)

**Comment by tom5454** [comment]
Couldn't reproduce it with the latest versions `0.6.8a`
