### ISSUE TITLE
Animation breaking

### ISSUE THREAD

**Issue by CLittleLunaC** [tom5454/CustomPlayerModels#44]
okay this issue is making the mod unusable to me, I was given tips on how to fix it but after the last update, they break permanently, resorting to me either deleting the problematic frame or scrapping the entire animation entirely and staring from scratch 

this is the issue https://gyazo.com/13c26144f828e269761cfec2294ecdca

**Comment by tom5454** [comment]
Please post your project file.

**Comment by CLittleLunaC** [comment]
it isn't letting me post the project file here so I'll put it on google drive

Here it is https://drive.google.com/file/d/1s3VRtlss64ifuELPB2TJxHBvugqbQ2t5/view?usp=sharing

**Comment by tom5454** [comment]
I can't open the drive link, also if you zip the project file you can post it on Github.

**Comment by CLittleLunaC** [comment]
[Test1.zip](https://github.com/tom5454/CustomPlayerModels/files/6190862/Test1.zip)
 Sorry, about the Google drive not working, I dont use github often so I'm never sure what files can be uploaded
