### ISSUE TITLE
[Enhancement] X Axis Camera Offset

### ISSUE THREAD

**Issue by Sploggers** [tom5454/CustomPlayerModels#440]
When the head of the player model is moved forward the eye position remains the same. This is especially noticeable on quadrupedal models, as the camera is centered on the body and not the head.

If added it would be ideal to have the position of both first and third person cameras as a part, and the ability to move it from its pivot point like with normal parts, if that makes sense.

**Comment by tom5454** [comment]
You can move the whole body using Scaling/Model Display. Move the model to the eye postion. Minecraft doesn't have the ability to move the camera like that easily, and it would be picked up by serverside anticheat anyway.
With Pehkui you can adjust the eye height and third person camera distance (it's a separate mod).
