### ISSUE TITLE
Gui crash. NullPointerException. Minecraft 1.16.5 Fabric 0.14.19 CPM 0.6.8a 

### ISSUE THREAD

**Issue by Bob-of-the-Dead** [tom5454/CustomPlayerModels#441]
Editor crashes on main menu when pressing open skin editor button. Game still runs.

Error in init gui: java.lang.NullPointerException.

Only mods are Fabric Loader, Fabric api and CPM

https://paste.ee/p/Fl1K9

**Comment by tom5454** [comment]
Buy the game
