### ISSUE TITLE
Texture-based glowing parts keep flashing

### ISSUE THREAD

**Issue by HyperBeast43** [tom5454/CustomPlayerModels#449]
![cpm flashing](https://github.com/tom5454/CustomPlayerModels/assets/45052445/b711138d-e45d-423f-a569-36bd372d20c5)
Everything that uses the Color mode isn't flashing, but as soon as I use Texture, it goes berserk.

**Comment by tom5454** [comment]
What minecraft version are you using? And whats your mod list?

**Comment by wackiestwow** [comment]
i am assuming this is the latest version, because i have the same issue on 1.20.1 fabric (all mods are updated). for me it seems to only flicker when it is rendered on top of other parts (if the glowing part is half in front of the head and half not, the part over the head flickers constantly)

**Comment by tom5454** [comment]
Add 0.01 to the MCScale of the glowing part, to prevent z-fighting.
