### ISSUE TITLE
Crash when I try to add the API to my mod

### ISSUE THREAD

**Issue by Willsbam** [tom5454/CustomPlayerModels#451]
Title says it all, I've been trying to make a mod using CPM for a while. I know the project itself works, I've been making a general menu and have the player capabilities set up but the instant I try to use the API in my environment I can't launch the game. I've tried 1.19.2, then thought ah maybe the version is wrong I changed my project to 1.19.3, same issue, tried a fresh install on 1.20, same issue slightly different timing it looks like.  I can use and see the cpm code(I don't know the technical term for it alright) in my mod, it's just launching that bugs out. I've looked at the logs and It seems to begin failing when it gets to mixins and can't find directories, I haven't touched mixins so I have no idea what it's saying. I think I correctly followed the tutorial on the api documentation, so I have no idea what it could be at this point.
[CPM Mixin error log.txt](https://github.com/tom5454/CustomPlayerModels/files/11911945/CPM.Mixin.error.log.txt)

[CPM Mixin error log1.txt](https://github.com/tom5454/CustomPlayerModels/files/11912028/CPM.Mixin.error.log1.txt)
Any help would be greatly appreciated

**Comment by tom5454** [comment]
Add these to your run configs in your build.gradle
```gradle
property 'mixin.env.remapRefMap', 'true'
property 'mixin.env.refMapRemappingFile', "${buildDir}/createSrgToMcp/output.srg"
```
or use the [MixinGradle plugin](https://github.com/SpongePowered/Mixin/wiki/Mixins-on-Minecraft-Forge#step-1---adding-the-mixingradle-plugin) only follow step 1 of the tutorial. 
Then regen runs.
