### ISSUE TITLE
Having CPM installed causes pehkui scaling persistence to break

### ISSUE THREAD

**Issue by Rolahr** [tom5454/CustomPlayerModels#452]
This one has been around for a while but I've never thought to make a post here about it for some reason. This is especially annoying as I make datapacks for the origins mod, which means I cannot use CPM while working on anything that affects scale.

**Comment by Annie-nyan** [comment]
I have tried setting Pehkui's scale persist to true using both config and commands, I even tried using cpm-server-config.json to no avail. My scales just won't persist.

**Comment by netcore10** [comment]
Can confirm if you remove CPM serverside the issue is fixed.
