### ISSUE TITLE
Recolorable Parts

### ISSUE THREAD

**Issue by Crispot123** [tom5454/CustomPlayerModels#454]
What I wanted to see is being able to recolor parts of a model like the sheep texture and have colors changed by animation witch can allow players to create a fire person having their colors changed by freezing or just recreating the 'jeb_' easter egg with their model
![CPM Recolor](https://github.com/tom5454/CustomPlayerModels/assets/62366919/3399b237-bb9d-4412-b094-ba42059ad77c)

**Comment by tom5454** [comment]
Add the `Effects/Color Filter`, then you can animate the color for that cube.
