### ISSUE TITLE
[Bug] shrek's divine abilities include creation of wormholes

### ISSUE THREAD

**Issue by donaldjuniortrump** [tom5454/CustomPlayerModels#455]
[demonstration](https://www.youtube.com/watch?v=RGdn26mGaLw)
toggling rendering on a model with wide hitbox shifts player southeast, potentially into/through walls

1.16.5 forge 36.2.39
mod version 0.6.8a

**Comment by tom5454** [comment]
This is an issue with Pehkui, toggling rendering just sets/resets your pehkui attributes.
