### ISSUE TITLE
mod incompatibility with Mowzie's Mobs

### ISSUE THREAD

**Issue by Inonedn** [tom5454/CustomPlayerModels#47]
Using the axe of a thousand metals disables rendering of the player's extra parts

**Comment by tom5454** [comment]
From looking at the source code Mowzie's Mobs replaces the player renderer, and doesn't post `RenderPlayerEvent`s when rendering.

**Comment by Jusey1** [comment]
^
Ye'h, this is an issue on Mowzie's Mobs side.
