### ISSUE TITLE
[Feature] Allow OSC to accept data from non-local IPs

### ISSUE THREAD

**Issue by RedRain0o0** [tom5454/CustomPlayerModels#477]
The current OSC input (afaik) only allows Ports. It'd be nice to allow external IPs for things like face tracking.

**Comment by tom5454** [comment]
You have to put your computer's IP into the program that's sending the data. The OSC input is a server and only needs a port.

**Comment by RedRain0o0** [comment]
oh wait, for real? thats sick! thanks
