### ISSUE TITLE
[Suggestion] Thought of a problem that could stop this mod from being used on servers

### ISSUE THREAD

**Issue by Manoanoob** [tom5454/CustomPlayerModels#48]
Someone can make a huge model that hides the player hitbox and use it in game to have an advantage. This discourages use on servers which is why most people download mods so you should add a feature to disable other peoples custom models. Or do something with hitboxes idk [https://imgur.com/a/7CaZsLB](url)

**Comment by Oakstar519** [comment]
There's already an option in the mod to stop rendering models. You can find it in the Gestures menu-- I think the default hotkey is R.

**Comment by Manoanoob** [comment]
> There's already an option in the mod to stop rendering models. You can find it in the Gestures menu-- I think the default hotkey is R.

I meant for specific people

**Comment by GrapeseedStudios** [comment]
I think that would be really useful! also.. you know... given the powerful nature of this mod, as it picks up steam someone's bound to make a penis. I would like to not see any penises in my bedwars game. thank you for coming to my ted talk
