### ISSUE TITLE
Animated textures freeze on last frame

### ISSUE THREAD

**Issue by Widget365** [tom5454/CustomPlayerModels#484]
Not visible in the editor, but in-game animated textures will have a minor lag on the last/first frame where it loops around. Is there a fix or a setting I'm not aware of??
In editor:
https://i.gyazo.com/dd856bde6fec761b8d5aa61a726dfb88.mp4

In game:
https://i.gyazo.com/3e5b1bc7b722ae7bd11511fe7168d30f.mp4

**Comment by tom5454** [comment]
Please send a screenshot of your texture sheet with the animated texture highlighted.

**Comment by Widget365** [comment]
![image](https://github.com/tom5454/CustomPlayerModels/assets/114877924/7c45c38f-283a-40f1-8d8c-60bb61c1cd74)

**Comment by tom5454** [comment]
Your yellow and white areas overlap, which causes the first frame to duplicate, this is only visible in-game and not in the editor.
The next version will have a warning if these areas overlap.
