### ISSUE TITLE
crash when opening gui

### ISSUE THREAD

**Issue by Tidzisi** [tom5454/CustomPlayerModels#505]
while running the game, everything was going well, the game started normally, but when I pressed the button to launch the gui, a message appeared that a crash had occurred and that I should send the log to github of this mod, the game itself did not crash, only the gui was replaced by the previously mentioned message.
[latest.log](https://github.com/tom5454/CustomPlayerModels/files/12871613/latest.log)

**Comment by tom5454** [comment]
Remove `cosmetica`
Duplicate of https://github.com/tom5454/CustomPlayerModels/issues/261
