### ISSUE TITLE
Constantly crashing on servers.

### ISSUE THREAD

**Issue by Ultmate-Mario** [tom5454/CustomPlayerModels#51]
I have only tested on hypixel so far but in the newest version (0.0.10c) I can't even get into the server. on version 0.0.9b I was able to do everything but open the player menu probably because of a player head issue in the menu. I will probably test this on other servers at some point.

**Comment by tom5454** [comment]
Please post your crash report.

**Comment by Ultmate-Mario** [comment]
[crash-2021-03-25_10.19.14-client.txt](https://github.com/tom5454/CustomPlayerModels/files/6207306/crash-2021-03-25_10.19.14-client.txt)
[crash-2021-03-25_10.23.07-client.txt](https://github.com/tom5454/CustomPlayerModels/files/6207307/crash-2021-03-25_10.23.07-client.txt)
[crash-2021-03-25_10.25.21-client.txt](https://github.com/tom5454/CustomPlayerModels/files/6207308/crash-2021-03-25_10.25.21-client.txt)
[crash-2021-03-25_10.16.26-client.txt](https://github.com/tom5454/CustomPlayerModels/files/6207309/crash-2021-03-25_10.16.26-client.txt)
[crash-2021-03-25_10.17.14-client.txt](https://github.com/tom5454/CustomPlayerModels/files/6207310/crash-2021-03-25_10.17.14-client.txt)

**Comment by tom5454** [comment]
Please post your minecraft log as well.

**Comment by Ultmate-Mario** [comment]
The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Rendering entity in world
Exit Code: -1

This happened when I went over the collectables chest in hypixel, it let me in the server this time but I didn't even open the collectables menu.

Also, here is the latest crash report where this happened.
[crash-2021-03-25_14.05.17-client.txt](https://github.com/tom5454/CustomPlayerModels/files/6207884/crash-2021-03-25_14.05.17-client.txt)

**Comment by Manoanoob** [comment]
> I have only tested on hypixel so far but in the newest version (0.0.10c) I can't even get into the server. on version 0.0.9b I was able to do everything but open the player menu probably because of a player head issue in the menu. I will probably test this on other servers at some point.

If you are using this mod on 1.16 you can't be on hypixel. If you want to use this mod on hypixel you MUST be on 1.8
