### ISSUE TITLE
[visual bug] Right hand blocks not positioned properly when modded

### ISSUE THREAD

**Issue by Trickster-4** [tom5454/CustomPlayerModels#516]
I made this custom right hand pose where the character is holding blocks like an Enderman.
it looks nice with vanilla blocks, but for some reason the modded blocks like custom wood types and more don't get positioned properly.
![image](https://github.com/tom5454/CustomPlayerModels/assets/90531548/38e20334-fec1-42ca-ad04-846e6e0b560f)
here's the character holding a wood log, the block is positioned properly. looks exactly how I made it look on the editor
![image](https://github.com/tom5454/CustomPlayerModels/assets/90531548/48e7e152-d106-45c9-ba36-f4825c7bbe8c)
and here's the character holding a plank of a custom wood type from Oh the biomes you'll go. as you can see it is not positioned properly. 

any way to fix this? I believe it looks like it is not checking the rotation angles.

**Comment by tom5454** [comment]
The item has the wrong third person rotations, you can make a resource pack or report it to the mod author.
The difference should be visible even with a vanilla model.
