### ISSUE TITLE
Both of my character's legs are in the centre of my torso rather than being spaced apart.

### ISSUE THREAD

**Issue by ThatDuck09** [tom5454/CustomPlayerModels#519]
I recently added Customizable player models to a modded server with friends.
When I logged back on after adding this mod, my characters legs were in the centre of my body. I tried several different models and they all had the same issue. This is only affecting me. 
The mods I'm using are:
Animal Origins - infinite origins
Cloth Config API Fabric/Forge
CorgiLib
Customizable Player Models Fabric
Doctor Who Regenerations
Extra Origins
Fabric API
Geckolib
Journey Map
Lato Origins
Medieval Origins
Mob Origins
Oh the Biomes you'll go refabricated
Origins Fabric
Origins Extra Keybinds
Pekhui
Tardis Refined
Terrablender Fabric

Does anyone know how to fix this?

![2023-10-25_22 42 15](https://github.com/tom5454/CustomPlayerModels/assets/127122018/4551fae4-97c9-41a1-a6f9-65016c6e43b6)

**Comment by tom5454** [comment]
It's probably `Doctor Who Regenerations` conflicting.
