### ISSUE TITLE
Loading a CPM Avatar in a Singleplayer World with Vivecraft causes crashing issues.

### ISSUE THREAD

**Issue by er1cw05** [tom5454/CustomPlayerModels#520]
This is just something I've deduced from a Modpack. People who made the modpack said to report it here. Here's the crash log.

[crash-2023-10-26_18.23.59-client.txt](https://github.com/tom5454/CustomPlayerModels/files/13193290/crash-2023-10-26_18.23.59-client.txt)

**Comment by tom5454** [comment]
Update ViveCraft
