### ISSUE TITLE
second/outer skin layer for hd skin not showing up

### ISSUE THREAD

**Issue by kropotkinnie** [tom5454/CustomPlayerModels#521]
Read other answers that told me to just add a second layer through tools> Add 2nd Layer. I've done so but I can't see how to actually add the textures for that layer. Also am I supposed to be sizing up and offsetting the second layer (hats/jackets/sleeves) if I want it to show up? My lower layer shows up just fine but I can't even figure out how to edit the 2nd layer I've added, let alone how to give it the correct textures.

**Comment by tom5454** [comment]
You have to edit the newly created cubes to match your texture sheet.

Please join the discord for support questions: https://discord.gg/mKyXdEsMZD
This site is for crash/bug reports and suggestions.
