### ISSUE TITLE
Crash with Oculus

### ISSUE THREAD

**Issue by PulsarFox** [tom5454/CustomPlayerModels#531]
I think i've got the same bug that was in this ticket : https://github.com/tom5454/CustomPlayerModels/issues/506 

But this time it's not with Iris, it's with Oculus (but well, it's an Iris fork)

Minecraft Version : 1.18.2
Forge : 40.2.10
CPM : 0.6.13a
Oculus : 1.6.4

Here's the crash report : 
[crash-2023-11-21_00.11.25-client.txt](https://github.com/tom5454/CustomPlayerModels/files/13444308/crash-2023-11-21_00.11.25-client.txt)

**Comment by PulsarFox** [comment]
Update : this bug has been introduced in CPM version 0.6.11a, i've downgraded it to 0.6.10a and it works fine

**Comment by tom5454** [comment]
0.6.11a added a fix for glowing hands/player heads with iris/oculus.
I tested with the exact same versions and it doesn't crash for me. Try looking for a mod that touches player head rendering.
