### ISSUE TITLE
How do I turn this off?

### ISSUE THREAD

**Issue by foxya27** [tom5454/CustomPlayerModels#534]
**My server is offline and it's annoying me and the players, how can I turn off this message?**
[CPM] Your in-game UUID is incorrect, the server is probably in offline mode. Models may not load.

**Comment by foxya27** [comment]
My friend and I translated the mod, it is quite good and I will be grateful if you add it!
[ru_ru.json](https://github.com/tom5454/CustomPlayerModels/files/13576802/ru_ru.json)

**Comment by The-Weeb-Guy** [comment]
you get rid of that message by making your server not offline, CPM uses minecraft UUIDs (attached to minecraft accounts) to handle things like skin exports and toms pastes exports.
