### ISSUE TITLE
Crash upon custom head being rendered in inventory GUI

### ISSUE THREAD

**Issue by nicco1690** [tom5454/CustomPlayerModels#538]
When my head (username: Confabulate if it's needed) is rendered in an inventory GUI when I have custom model rendering on, it immediately crashes the game. The crash log is provided below:

[crash-2023-12-29_15.53.59-client.txt](https://github.com/tom5454/CustomPlayerModels/files/13795974/crash-2023-12-29_15.53.59-client.txt)

- OS: Arch Linux x86_64
- GPU: Intel UHD Graphics 630
- Mod loader: Fabric
- Mod list: ask for the list
- Game version: 1.20.2
- Mod version: 0.6.13a

**Comment by AshiraLOL** [comment]
Had the same problem with Sodium.
Downgrading the Sodium version fixes the problem.

Custom head work without crashes only in Sodium version 0.5.3 and lower.

- Tested it on 1.20.2 Fabric (fabirc v.0.15.0)
- Tested with cpm and sodium mod only.
- The game crashes when rendered Custom head is displayed in the gui or on the armor stand. 
( If the custom head isn't visible or the model doesn't load, the game won't crash. )

**Comment by yoshiyoshyosh** [comment]
can replicate as well--same exact stacktrace. downgrading to 0.5.3 sodium does indeed fix the problem
