### ISSUE TITLE
Animations do not work on 1.8 

### ISSUE THREAD

**Issue by Manoanoob** [tom5454/CustomPlayerModels#54]

**Comment by tom5454** [comment]
It works for me. Please post more info. (Custom poses or gestures don't really work on Hypixel, if thats the issue.)

**Comment by Manoanoob** [comment]
> It works for me. Please post more info. (Custom poses or gestures don't really work on Hypixel, if thats the issue.)
Yeah it does not work on hypixel it works on single player though.
