### ISSUE TITLE
cpm fabric 1.20.4 0.6.14a crashes with iris on 1.20.4 fabric

### ISSUE THREAD

**Issue by asweqr** [tom5454/CustomPlayerModels#544]
simply putting iris together with its requirements and cpm causes the game to crash before loading the main menu

mods being used

CustomPlayerModels-Fabric-1.20.4-0.6.14a
fabric-api-0.93.1+1.20.4
sodium-fabric-mc1.20.3-0.5.5
iris-mc1.20.4-1.6.14
indium-1.0.28+mc1.20.4

logs
[latest.log](https://github.com/tom5454/CustomPlayerModels/files/13924321/latest.log)
[crash-2024-01-13_10.49.56-client.txt](https://github.com/tom5454/CustomPlayerModels/files/13924324/crash-2024-01-13_10.49.56-client.txt)

**Comment by Chiboski** [comment]
I have the same issue, Hoping this will get fixed soon.

Bump

**Comment by MerlinK11** [comment]
same for me :(
