### ISSUE TITLE
[Blockbench/Export] Additional Cloned Base Parts Merge into Base 

### ISSUE THREAD

**Issue by CarJem** [tom5454/CustomPlayerModels#552]
I have an issue with the plugin that seems rediculous... I intentionally have this duplicate body part I made in CPM.... and when I need to export it from Blockbench it tries to merge it with base part...
I need to have it this way so I can have seperate positions and animations on a root layer....

And looking at the source code indicates that this is a flaw with the plugin itself....
https://github.com/tom5454/CustomPlayerModels/blob/127e1390abba5e832729e6e12c3235d4b50731df/Web/src/blockbench/java/com/tom/cpm/blockbench/convert/BlockbenchExport.java#L229C4-L246C5
```java
//Line 229 to 246
//file: ./Web/src/blockbench/java/com/tom/cpm/blockbench/convert/BlockbenchExport.java
                        if(groupName.endsWith("_dup")) {
                                groupName = groupName.substring(0, groupName.length() - 4);
                                part = part(groupName);
                                if(part == null) {
                                        rootWarning(group);
                                        return;
                                }
                                ModelElement e = new ModelElement(editor, ElementType.ROOT_PART, part);
                                editor.elements.add(e);
                                me = e;
                        } else {
                                part = part(groupName);
                                if(part == null) {
                                        rootWarning(group);
                                        return;
                                }
                                me = getPart(part);
                        }
```

Blockbench Preview
![image](https://github.com/tom5454/CustomPlayerModels/assets/18092668/b28669ad-3a9f-4897-8210-02bb1beffe57)

Pre-Blockbench Model:
![image](https://github.com/tom5454/CustomPlayerModels/assets/18092668/1c1ececc-01ad-4d4f-b86d-c0b203995c15)

Post-Blockbench Model Structure:
![image](https://github.com/tom5454/CustomPlayerModels/assets/18092668/7eb0a6b6-b612-4a9a-9666-0232570a442a)

**Comment by tom5454** [comment]
This is fixed in the latest version `0.6.14_pre2`.
