### ISSUE TITLE
First person animation not playing with the first person model mod

### ISSUE THREAD

**Issue by Kittybit1** [tom5454/CustomPlayerModels#557]
I have it set so that the neck and head turn invisible when rendering in first-person, but the animation is not playing in the newest release.

(please excuse the laggy video, i had like 10 different things open while recording)

![image](https://github.com/tom5454/CustomPlayerModels/assets/83882774/5189312e-71d9-473d-abd7-dbcdb7def6d8)

https://github.com/tom5454/CustomPlayerModels/assets/83882774/eadad49b-5554-4d17-8d6d-6309ad023233

![image](https://github.com/tom5454/CustomPlayerModels/assets/83882774/ee1ffe2f-72cd-4b0d-ab27-d78f84f81a3b)

here is the mod list as well

**Comment by tom5454** [comment]
Update `first person model` 2.3.0 made breaking changes and changed the mod id.

**Comment by Kittybit1** [comment]
ohh, i see!! thank you
