### ISSUE TITLE
Crash Upon Rendering Model Head items

### ISSUE THREAD

**Issue by AzuryxxVortex** [tom5454/CustomPlayerModels#560]
Hello, I'm having an issue where the dropped heads of modified player models just instantly crash the game.

I'm not sure if this is a mod compatibility issue, but I do use Embeddium, Oculus and Lazurite.. So most likely.
Here's the latest log - 
[latest.log](https://github.com/tom5454/CustomPlayerModels/files/14186589/latest.log)

Unsure if this place is the right one but I'd be honoured to have some pointers from experienced people-
Have a good day.

**Comment by tom5454** [comment]
Embeddium made a breaking change into skull rendering, downgrade to `0.3.0`

**Comment by AzuryxxVortex** [comment]
Thanks for the info! Will do.
