### ISSUE TITLE
1.20.1 - Can't open Minecraft with CPM installed. 

### ISSUE THREAD

**Issue by elslimecicle** [tom5454/CustomPlayerModels#562]
I've removed every mod and the only thing that fixes the client crashing is by removing CPM. I have it installed on a server, and that starts up fine, but my client won't open at all.

[crashreport.txt](https://github.com/tom5454/CustomPlayerModels/files/14228462/crashreport.txt)

**Comment by tom5454** [comment]
Remove `cosmetica`
Duplicate of #261
