### ISSUE TITLE
The default model is visible when changing models with the command

### ISSUE THREAD

**Issue by alumina6767** [tom5454/CustomPlayerModels#564]
Hello! Thank you for the wonderful mod.
I see the default model when I change the model with the /cpm command. Is there any way to prevent this?

It seems that if the model is not cached, the default model is visible for a longer time.

I am using CustomPlayerModelsFabric-1.20.2 v0.6.14b fabric.
I am Japanese, so please excuse the machine translated text...

https://github.com/tom5454/CustomPlayerModels/assets/85728971/fd310aee-3c25-404c-a558-f9eb0c7a0123

**Comment by tom5454** [comment]
Merge all of your models into one, and use toggle animations with the command controlled flag. Then set the toggle animations with [`/cpm animate` command](https://github.com/tom5454/CustomPlayerModels/wiki/The--cpm-command#animate)

The models are loaded in the background, and in most cases from the network or from the local cache, but that still needs file parsing, texture loading etc.

**Comment by alumina6767** [comment]
Thank you for your answer!
In this example, the model was thicker and thinner, but if I frequently replace a model with a very different shape, do I still have to merge it into one model?
For example, changing from a whale to a pig.

**Comment by tom5454** [comment]
If you really want to avoid the less then 1 second load time, then yes.
Or give the player 1 or 2 seconds of invisibility, and spawn some particles, to hide the model change.

**Comment by alumina6767** [comment]
Thank you for your thoughtful reply!
I will try to work on this in a creative way using layer toggles and animations.
