### ISSUE TITLE
Render system isn't initialized correctly

### ISSUE THREAD

**Issue by NachoIannizzotto** [tom5454/CustomPlayerModels#565]
I was working on my own model for CPM and when I import it into my server, my friends see me as a Steve with a error on top of my head, the error log on the editor drops this:
![imagen_2024-02-10_180640210](https://github.com/tom5454/CustomPlayerModels/assets/60115738/94c58f3b-4d4e-4780-88b8-db138f7dc68f)

I'm still unsure what's wrong. This is the log as well.
[logs.json](https://github.com/tom5454/CustomPlayerModels/files/14230519/logs.json)

**Comment by tom5454** [comment]
Try removing `apoli`, and any mods that depend on it.

**Comment by tom5454** [comment]
Dou you have any morph like mods installed?
The game is trying to render the armorstand model when this error is happening.
