### ISSUE TITLE
Can the model uploaded to the paste website be downloaded again?

### ISSUE THREAD

**Issue by AssestinaR** [tom5454/CustomPlayerModels#568]
I edited this model on my old computer and uploaded it to the paste website, but my old computer is no longer usable. I want to download my model again from the paste website, but I can't find where to download it

--This message was translated by a translation website. I'm sorry if the tone offended you

![{2BA3C086-F438-4ada-8BFC-2B194A16C9B6}](https://github.com/tom5454/CustomPlayerModels/assets/93767547/845f2556-05fe-429a-97be-95f8dc7f7aa0)

**Comment by AssestinaR** [comment]
![{5A844459-BCED-4a87-B9F5-56BA25E110E7}](https://github.com/tom5454/CustomPlayerModels/assets/93767547/e6d40968-5667-4b1e-81e9-9d51ee7a444c)
If it is not convenient for your website to add such a feature, can you help me manually download this model? I really need it,

**Comment by Lunar-Pixel** [comment]
Exports are not able to be restored or made editable, keep your project file safe if you want to be able to edit your model.

**Comment by AssestinaR** [comment]
> Exports are not able to be restored or made editable, keep your project file safe if you want to be able to edit your model.

This terrible fact saddens me, perhaps I can only manually create another one based on the original model myself.

**Comment by Lunar-Pixel** [comment]
> > Exports are not able to be restored or made editable, keep your project file safe if you want to be able to edit your model.
> 
> This terrible fact saddens me, perhaps I can only manually create another one based on the original model myself.

It's moreso to stop people from just stealing peoples models easily and not really anything else,

**Comment by AssestinaR** [comment]
> > > Exports are not able to be restored or made editable, keep your project file safe if you want to be able to edit your model.
> > 
> > 
> > This terrible fact saddens me, perhaps I can only manually create another one based on the original model myself.
> 
> It's moreso to stop people from just stealing peoples models easily and not really anything else,

You're right.
