### ISSUE TITLE
Export mode not working properly

### ISSUE THREAD

**Issue by ThatOneTrainLover** [tom5454/CustomPlayerModels#569]
When I downloaded a .cpmproject from the free models chat, and it got uploaded to model editor, when trying to export the project as model the gui was broken, and there was no option to export as other and template. no other mods used. version 0.6.14c (1.19.2)

**Comment by ThatOneTrainLover** [comment]
A minor problem with the file itself

**Comment by tom5454** [comment]
You have a template project. Use Edit/Tools/Convert to Model.
