### ISSUE TITLE
torso glitch

### ISSUE THREAD

**Issue by f0sch13r4** [tom5454/CustomPlayerModels#570]
There is an error in which the torso of my default skin keeps appearing even though I hide it, it seems that the model's skin does not change the default torso. This error only happens with the skin's torso
![Uploading imagem_2024-02-21_232401082.png…]()

**Comment by tom5454** [comment]
Your screenshot wasn't uploaded correctly.

**Comment by FelisMoon** [comment]
I suspect this may be related to (#323)
