### ISSUE TITLE
Crash with Origins mod in fabric 1.20.1

### ISSUE THREAD

**Issue by Tempest-5ky** [tom5454/CustomPlayerModels#573]
Due to an issue with rendering the custom model playerhead in the origin selection screen, the game crashes.

Crashlog: https://mclo.gs/YYrEnXd

CPM version: 0.6.14b
Origins version: 1.10.0
Game version: Fabric 1.20.1

**Comment by tom5454** [comment]
Update CPM to `0.6.14c`
