### ISSUE TITLE
Error with GUI (with Minecraft log included)

### ISSUE THREAD

**Issue by CanisArctosLupus** [tom5454/CustomPlayerModels#576]
[2024-03-03-2.log.gz](https://github.com/tom5454/CustomPlayerModels/files/14472631/2024-03-03-2.log.gz)

Error: Error drawing gui: java.lang.nosuchmethoderror: 'void net.coderbot.batchedentityrendering.impl.blendingstateholder.settransparencytype(net.coderbot.batchededentityrendering.impl.transparencytype)'

I cannot open the GUI at all
![image](https://github.com/tom5454/CustomPlayerModels/assets/113195579/94fbb448-5834-4c33-81ef-f68d64c521e4)

**Comment by CanisArctosLupus** [comment]
Turns out it was Iris, any shader mod can cause this error

**Comment by tom5454** [comment]
Update CPM
