### ISSUE TITLE
Missing server side-mod/plugin Error

### ISSUE THREAD

**Issue by LupyGamesTTV** [tom5454/CustomPlayerModels#577]
I'm on a 1.20.1 modded forge server and i can use my custom models because the button on the bottom left is greyed out saying its missing even tho the mod is in the server files and installed on my end, i don't know why its doing this but its getting annoying i never had this issue on a server on 1.18.2
![Screenshot 2024-03-08 064202](https://github.com/tom5454/CustomPlayerModels/assets/154709140/d61a1829-828a-4ce5-a11d-b9b6df2f0c1d)
![Screenshot 2024-03-08 064220](https://github.com/tom5454/CustomPlayerModels/assets/154709140/7e45da6f-f6a7-451f-998c-8fd549b48059)
![Screenshot 2024-03-08 064343](https://github.com/tom5454/CustomPlayerModels/assets/154709140/d825c22f-d2e4-4692-acfb-4a98141bbf81)
![Screenshot 2024-03-08 064402](https://github.com/tom5454/CustomPlayerModels/assets/154709140/997131ec-6612-42e2-bdcb-e22b2a9dbe92)

**Comment by tom5454** [comment]
Please post your server's log
