### ISSUE TITLE
Model not disappearing when new model/skin is loaded

### ISSUE THREAD

**Issue by nullifi3d** [tom5454/CustomPlayerModels#580]
I'm writing this on behalf of a friend, as their minecraft is a little broken with CPM. 

The username is Chaithechuu. They were using a CPM model that was exported to save with the skin. However, when they put on a different skin, the model did not disappear. They did not load the model with this new skin, but the model still was there. We tried clearing the pastes, but the model was still there. I tried troubleshooting with what I knew about the mod, but nothing changed. 

Any help with fixing this would be helpful, and any information on how to avoid this in the future would be very helpful.

**Comment by tom5454** [comment]
I don't see their model on the Web Viewer (https://tom5454.com/cpm_viewer.html?name=Chaithechuu)
They might have a cpmmodel equipped. 
Open the Gestures Menu (G) and click on Models in the bottom right
Then click `Load from Skin` or `Reset Skin button in the models list.
