### ISSUE TITLE
Mod Bootloops on Startup

### ISSUE THREAD

**Issue by corvidtowers** [tom5454/CustomPlayerModels#582]
Starting on a 1.18.2 fabric curseforge profile, only mods alter client-side gameplay such as iris and sodium. Stuck on perpetual mojang loading screen over and over again when i start up my launcher.

**Comment by tom5454** [comment]
Please post your minecraft log

**Comment by corvidtowers** [comment]
It doesn't crash, it just perpetually loads.
[latest.log](https://github.com/tom5454/CustomPlayerModels/files/14749184/latest.log)

**Comment by tom5454** [comment]
Remove cosmetica
Duplicate of #261
