### ISSUE TITLE
Freezes on startup, with no errors

### ISSUE THREAD

**Issue by Zygahedron** [tom5454/CustomPlayerModels#60]
Minecraft 1.16.5, Fabric loader 0.11.3, Fabric API 0.32.5, CustomPlayerModels 1.16-0.0.10d
No other mods installed
[latest.log](https://github.com/tom5454/CustomPlayerModels/files/6267608/latest.log)

**Comment by tom5454** [comment]
Does it load without CustomPlayerModels, only with fabric api? Also check your `debug.log`, maybe it has something in it.

**Comment by Zygahedron** [comment]
Yes, it loads fine with only fabric api, and with 18 other mods without this one.
I can't seem to find debug.log, where is it?

**Comment by tom5454** [comment]
Nvm fabric doesn't write `debug.log`-s, thats a forge only thing. Try reinstalling fabric, I downloaded the exact same version and it works for me.

**Comment by Zygahedron** [comment]
No change after reinstalling the same version of fabric. I also tried running it in the standard minecraft folder instead of a different one, and that didn't help.

**Comment by tom5454** [comment]
Please test the latest version (0.0.13a).

**Comment by Zygahedron** [comment]
Yes, it does seem to be fixed, thank you!
