### ISSUE TITLE
Error connecting to paste site Faild to connect to Past side

### ISSUE THREAD

**Issue by M0xed** [tom5454/CustomPlayerModels#605]
![help pls](https://github.com/tom5454/CustomPlayerModels/assets/168459194/81f12ccc-1c2f-4aa6-853b-a904c20c445b)

i did what it saide and i cant concet to my friend server anymore because of it. it lods the moddle in singe player so im stuck un it

**Comment by FelisMoon** [comment]
Invalid Session errors are usually caused by connection problems, Offline/Pirated clients or clients that failed to login properly. Remember that because the skin export paste site uses player UUID and the skin system from Mojang/Microsoft accounts, failure to connect will yield this error.
