### ISSUE TITLE
Toggle/Value Animations no longer working after having 256 of them (combined)

### ISSUE THREAD

**Issue by The-Weeb-Guy** [tom5454/CustomPlayerModels#608]
Was adding custom holding animations for tools via OSC and it 'randomly' stopped working, till i checked my project file and noticed i had 257 different toggle/value animations for all of my models custom posing and other OSC features. Please raise this again, unless experimental exports fix that, in which model properties do not work at all. (Other people see all the sliders as messed up, for my models it means them turning into spaghetti monsters)

**Comment by tom5454** [comment]
CPM has 256 bytes of syncable data. Toggle layers currently use a full byte per layer and waste 7 bits. The experimental exporter will have a way to compact this down in the future. For now you can use a value layer with 256 frames to fully utilize the available bytes. Use a 0 to 256 value range and send the correct OSC number value. The CompassOSC module will need an update for this. Maybe create tags that has the number in the name: `$model:item/layer1/v2` for playing frame 2 for the animation `layer1`.
