### ISSUE TITLE
Latest CPM update crashes on loading for 1.12.2

### ISSUE THREAD

**Issue by FreianOfVoid** [tom5454/CustomPlayerModels#619]
I was running a modpack after updating the mod in minecraft version 1.12.2, and all of the sudden, I crashed, with the error code below.
![image](https://github.com/tom5454/CustomPlayerModels/assets/128076814/2272063b-be2c-441d-a250-43fd2fa74ec0)

How to replicate: run latest 1.12.2 Customizable Player Models update. Mod version 0.6.16d.

**Comment by tom5454** [comment]
Please post your minecraft log
Can't reproduce with just CPM in a 1.12.2 forge install.
