### ISSUE TITLE
[Suggestion] use model textures for `getLocationSkin()` (and `getLocationCape()` ?) (1.7.10)

### ISSUE THREAD

**Issue by kotmatross28729** [tom5454/CustomPlayerModels#627]
If a mod uses `AbstractClientPlayer.getLocationSkin()` to, for example, render hands, it will use `AbstractClientPlayer.locationSkin`, which is the vanilla mc skin. A suggestion is to modify `getLocationSkin()` (and possibly `getLocationCape()`?) to use the texture that is currently in use for the model. 

Examples: 

I have the skin installed via the CPM model,

![2024-06-13_22 42 22](https://github.com/tom5454/CustomPlayerModels/assets/110309314/f628e8df-a151-45eb-a3be-4155d6ae0548)

 and if I take an item that uses `getLocationSkin()` to render hands, it will render the vanilla mc skin, instead of the CPM skin.

![2024-06-13_22 42 32](https://github.com/tom5454/CustomPlayerModels/assets/110309314/8d0108ec-924a-47af-b3f7-5e11839c9f7c)

Or, in FTBUtilities, also uses `getLocationSkin()` for the head texture.

![2024-06-13_22 55 49](https://github.com/tom5454/CustomPlayerModels/assets/110309314/4fa27917-596e-44cc-b865-d6c60d721ff6)

But, interestingly, the map in hand is rendered precisely with the model’s texture, although it also uses `getLocationSkin()`, there is *probably* a manual patch for this, but after looking through the cpm code I didn’t find it (maybe I was looking poorly)

![2024-06-13_23 12 37](https://github.com/tom5454/CustomPlayerModels/assets/110309314/c5792106-90bc-4d32-9eae-c7a502776872)

Addition: сhanging `getLocationCape()` can fix the [problem](https://github.com/Roadhog360/Et-Futurum-Requiem/discussions/441) with the mod "Et Futurum Requiem" which ports elytras to 1.7.10, using `getLocationCape()` when render them

**Comment by tom5454** [comment]
That'll just break the texture, in the gun example cpm has to replace both the texture and hand model, so patching these methods wouldn't work, and just break stuff. CPM models don't have to follow the same UV map as vanilla.
For the 'Et Futurum Requiem' issue, there will be an API to render custom parts in the future. Also cape and elytra textures are different in CPM.
