### ISSUE TITLE
I can't use a model because of incorrect ending byte at 86852

### ISSUE THREAD

**Issue by Suushi000** [tom5454/CustomPlayerModels#633]
![image](https://github.com/tom5454/CustomPlayerModels/assets/88200847/b096c7c4-1a79-4f5a-8b21-3084ac6475c3)

**Comment by Suushi000** [comment]
https://github.com/Suushi000/Pinxe here it is! Thank you

**Comment by tom5454** [comment]
You have a new line at the end of your file, remove it.
