### ISSUE TITLE
Faulty Models

### ISSUE THREAD

**Issue by foxya27** [tom5454/CustomPlayerModels#635]
CustomPlayerModels-Bukkit v0.6.17b
Current Purpur Version: 1.21-2246-ad910f8 (MC: 1.21)*

https://pastebin.com/DYgA62ju

**Comment by tom5454** [comment]
Bukkit API implementation bug, report it to paper/purpur. The bukkit api still uses UUIDs, vanilla changed to resource locations in 1.21.
