### ISSUE TITLE
Jump overlaping pose animations

### ISSUE THREAD

**Issue by raykkitsune** [tom5454/CustomPlayerModels#636]
Jump animation overlap all pose animations even on cubes that wasn't touched on the jump animations animation

as you can see, i created a different cube for different types of pose animation, all of they having different positions, but its animations just got overlaped by jumping animation

https://github.com/tom5454/CustomPlayerModels/assets/144868335/ca7c895c-e733-4e1e-aa47-ef80abfd1f78

**Comment by tom5454** [comment]
The jump is a pose type animation. Only 1 pose animation can play at the same time, so it will overwrite all other pose animations. Conditional animations will be able to fix this in the future.
