### ISSUE TITLE
[Suggestion] A new type of custom animation? EDIT: Very probable solution found as of 4/18.

### ISSUE THREAD

**Issue by Nues** [tom5454/CustomPlayerModels#64]
I noticed that poses uses all the body parts when you only animate a few, making your character a little static.

I also noticed that gestures does only affect the animated parts, but they are timed and vanish.

I propose a third custom animations that are for more long-term uses, probably similar to a gesture that doesn't vanish until you toggle it off.

For example, let's say I animate the wings opened (no animation for opening them, transitional animations is not the topic I'm going to talk about) and I want them to keep being open until I toggle them back closed. In the time they are opened, I can still do various animations in the meantime.

This kind of animation can be used for the following:

- opened hand(s)/ closed hand(s) mode
- wings being extended/retracted
- tails being raised/lowered
- accessories (aka glasses/earrings/other) being worn/moved/removed (provided you have enough room to hide them)
- hairstyle being modified (via hairblocks like saiyans from Dragonblock C pre-transformation vs post-transformation)
- eyes being open/closed

- and various gestures that are held while in motion

I don't know what to call this type of animation, closest thing I can think of is "Actions"
Or maybe Gestures should be split to "Timed Gestures" and "Held Gestures"

**Comment by Oakstar519** [comment]
As a temporary fix, you can set a gesture to "Loop" and it'll stay in that position until you toggle it off.

**Comment by Nues** [comment]
Oof, such a good idea defeated by such a simple fix. All I can say is ingenious.
