### ISSUE TITLE
The model is not displayed for everyone on the server

### ISSUE THREAD

**Issue by Jodich-Avi** [tom5454/CustomPlayerModels#654]
I logged into a server that supports the Customizable Player Models mod, and those who already have this mod on the server do not see my model, although I see my model myself. I disabled the profile in the security settings, but it didn't help me, so he also writes that "Your in-game UUID is incorrect, the server is probably offline. Models may not load.". However, I saw another person's model, which is very strange. Help me figure this out
![Скриншот-08-08-2024 15_21_41](https://github.com/user-attachments/assets/65d4edd4-032a-495e-94e7-ef17cbd1c467)

**Comment by tom5454** [comment]
cpmmodels without UUID lock will load, skin encoded or UUID locked models won't.
