### ISSUE TITLE
[BUG] every cpm model texture turns white and then crashes the game

### ISSUE THREAD

**Issue by donaldjuniortrump** [tom5454/CustomPlayerModels#655]
i be mining my craft when suddenly: WHITE! the textures of all my customplayermodels models turn WHITE! i press my beloved f11 key, and the sky turns BLACK! the game then CRASHES! i blame you for this!

mod list:
CustomPlayerModels-1.16-0.6.15a
DistantHorizons-2.1.0-a-1.16.5
FirstPersonMod-2.0.1
Pehkui-3.7.8+1.16.5-forge
TRansliterationLib-1.0.4

1.16.5 forge 36.2.42

[2024-08-08-1.log](https://github.com/user-attachments/files/16552010/2024-08-08-1.log)

**Comment by tom5454** [comment]
You are getting an `OutOfMemoryError`. Increase the RAM for your game.
