### ISSUE TITLE
Gestures and poses occasionally cancel each other out

### ISSUE THREAD

**Issue by Oakstar519** [tom5454/CustomPlayerModels#66]
If you enable a custom pose followed by a gesture, then do anything that triggers a built-in pose (walking or crouching, for example) the custom pose will be disabled, but the gesture will keep playing. This doesn't happen while triggering a custom pose without also triggering a gesture.

**Comment by tom5454** [comment]
The animations are encoded into the skin layer settings, Only one can be encoded at the same time. The pose is saved so you can use both one pose and gesture, but when you move a vanilla pose overrides it.
