### ISSUE TITLE
Game crashes when rendering some models.

### ISSUE THREAD

**Issue by The-Weeb-Guy** [tom5454/CustomPlayerModels#668]
Updated CPM in a 1.12.2 pack i was playing and crashed the second my model rendered, was able to do the same in a 1.20.1 fabric testing modpack. I do not know which aspect of my models causes these issues as they both have alot of animations and a fair few cubes.

[crash-2024-09-01_11.33.19-client.txt](https://github.com/user-attachments/files/16829528/crash-2024-09-01_11.33.19-client.txt)
[crash-2024-09-01_11.38.55-client.txt](https://github.com/user-attachments/files/16829553/crash-2024-09-01_11.38.55-client.txt)

(sorry that i didnt report this during the beta test period, iv been fairly busy IRL)

**Comment by The-Weeb-Guy** [comment]
small note that i didnt have experimental exports on, and re-exporting or using test ingame gave the same issues

**Comment by tom5454** [comment]
I can't reproduce it with my models, how many value layers do you have?
Can you send me the project on discord (you can remove all of the cubes and texture, it shouldn't effect the crash).
