### ISSUE TITLE
issue with editing animations

### ISSUE THREAD

**Issue by Xigzagamer** [tom5454/CustomPlayerModels#67]
version- CustomPlayerModels-Fabric-1.16-0.0.11c

changing a pose to a gesture then testing in game and attempting to edit another animation crashes the game and reverts the animation back to being a pose.
(basically I accidentally made my animation as the standing pose when I meant to make it a gesture, but when I try to change it the mod crashes.)

(edit)
Apparently the crash happens whenever you hit the edit button after using the test ingame feature. Meanwhile the reverting animation type is another completely separate issue that happens if you so much as close the project and reopen it.

**Comment by tom5454** [comment]
Please test this in the new version, the test ingame feature was buggy in 0.0.11c, I couldn't reproduce it.

**Comment by Xigzagamer** [comment]
I tested it and it doesn't seem to happen in newer versions.
