### ISSUE TITLE
Game crashes when casting Gestures with Quick Access hotkeys

### ISSUE THREAD

**Issue by Kana-ise** [tom5454/CustomPlayerModels#670]
Game crashes when casting Gestures with Quick Access hotkeys pretty much

**Comment by Kana-ise** [comment]
this is in the newest release of 8 hours ago

**Comment by tom5454** [comment]
Please post your minecraft log

**Comment by bfreezie** [comment]
can second this. Here's my crashlog
[crash-2024-09-01_20.34.28-client.txt](https://github.com/user-attachments/files/16831985/crash-2024-09-01_20.34.28-client.txt)

Also, my test-in-game gestures menu has been replaced by this:
![2024-09-01_20 34 14](https://github.com/user-attachments/assets/cc6db3b8-4b81-4835-8889-037009d8afa3)

**Comment by raykkitsune** [comment]
same
https://mclo.gs/hM59vSy
