### ISSUE TITLE
Flashback compatability issues

### ISSUE THREAD

**Issue by clapyblappy** [tom5454/CustomPlayerModels#676]
I am working on a video where I want to do a silly skateboard montage, and customplayermodels has been the most user friendly and perfect animation poser for my skateboard pose in elytra. The only issue is that the mod I use to record replays flashback, isn't showing the special animation. Moulberry (dev of flashback) said that it might be related how packets get recorded from flashback vs how its done through cpm. as the c2s wouldnt be recorded in the flashback recording or something. I am no technical person so excuse me if I am confusing, but i would love for this to be addressed if it is a customplayermodels issue, as figura works with flashback but I am not skilled in that mod, and prefer cpm. Anyways thanks for reading :)

Link to moulberrys stream where he discussed this with me starting around 45 minutes in: https://www.twitch.tv/videos/2244014418

**Comment by tom5454** [comment]
I tested flashback, you have to use the skin export option to show up in flashback.
I'm looking into making an addon mod that adds compatibility with how the packets are recorded.

**Comment by clapyblappy** [comment]
That would be amazing -- I did use the skin export option but it wasn't showing up for me still unfortunately. I am using it only clientside its not on server, that might be why.

**Comment by clapyblappy** [comment]
Thank you so much for your fast return, this is amazing much love. You are a boss
