### ISSUE TITLE
Error processing mouse event

### ISSUE THREAD

**Issue by JonSa789** [tom5454/CustomPlayerModels#700]
I'm trying to export the model I did but the "Export" botton didn't work. There's no problem with any other one but just with the export one.
In the logs looks like it printed Error procesing mouse event each time I tried pressing it.
I have exported the logs and uploaded them here.

[cpm-errorlog-2024-10-26.zip](https://github.com/user-attachments/files/17530625/cpm-errorlog-2024-10-26.zip)

Mod version: 1.20-0.6.18a

**Comment by tom5454** [comment]
Update the mod, this was an issue with the `0.6.18` versions.
