### ISSUE TITLE
crash on startup with iris enabled fabric 1.21.3

### ISSUE THREAD

**Issue by AnukWarrior** [tom5454/CustomPlayerModels#701]
running cpm with iris on 1.21.3 will cause the game to crash on startup

[latest.log](https://github.com/user-attachments/files/17531774/latest.log)

[crash-2024-10-27_08.46.35-client.txt](https://github.com/user-attachments/files/17531776/crash-2024-10-27_08.46.35-client.txt)

**Comment by Lavengale** [comment]
I had this issue too
