### ISSUE TITLE
Error when trying to upload skins or access pastes.

### ISSUE THREAD

**Issue by taycat34** [tom5454/CustomPlayerModels#705]
1.16.5 Fabric
The following message appears when I try to upload/export skins, or access my pastes.

"Unknown network error, while connecting to the paste site.
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to rquested target"

**Comment by tom5454** [comment]
You have to use a more up-to-date version of java 8 with your Minecraft 1.16 installation. 
By default the Minecraft Launcher ships a Win7 version of java with the launcher and it can't connect to most websites anymore.
