### ISSUE TITLE
Incompatibility with the next vivecraft upodate, because of internal changes

### ISSUE THREAD

**Issue by fayer3** [tom5454/CustomPlayerModels#716]
Hi, vivecraft dev here. then next vivecraft version will have some internal changes, which breaks this mixin 
https://github.com/tom5454/CustomPlayerModels/blob/master/CustomPlayerModels-1.20.4/src/platform-shared/java/com/tom/cpm/mixin/compat/VRArmRendererMixin_%24vivecraft.java#L50-L65

because I renamed that method from `renderItem` to `renderHand`

am I correct in the assumption that if we directly use the `getTextureLocation` method to get the skin this wouldn't be needed?
if so I can change that to that.

**Comment by tom5454** [comment]
Yes, that's correct.

**Comment by fayer3** [comment]
okay, then I'll change the skin fetch to that. if you could make that redirect optional, so that the game doesn't break. that would be great

**Comment by StarleetTW** [comment]
tom, fix it please

**Comment by fayer3** [comment]
> okay, then I'll change the skin fetch to that. if you could make that redirect optional, so that the game doesn't break. that would be great

I did that btw here https://github.com/fayer3/VivecraftMod/commit/1244e0c9061de6e86c4540bf9fa9285e1f372091
that will be in vivecraft 1.2.0

**Comment by mb443333** [comment]
This still happens in 1.20.1, if you could please update that version as well so that it doesn't crash I would greatly appreciate it.
