### ISSUE TITLE
How to load skin/model? Does it require Minecraft premium?

### ISSUE THREAD

**Issue by adiee5** [tom5454/CustomPlayerModels#72]
i have no idea how am i supposed to load the skin and play with it

**Comment by Oakstar519** [comment]
It does require premium. You load the model by using a skin with the data written into the unused space, which the mod will automatically export.

**Comment by adiee5** [comment]
is there any option for non premium players?

**Comment by tom5454** [comment]
Updated the wiki: https://github.com/tom5454/CustomPlayerModels/wiki/Exporting#exporting-as-local-model
