### ISSUE TITLE
jump height stat does not function with pehkui installed on 1.21.1 fabric

### ISSUE THREAD

**Issue by AnukWarrior** [tom5454/CustomPlayerModels#728]
when pehkui is installed the jump height stat stops functioning for playermodels scaling settings

https://github.com/user-attachments/assets/591afd0b-8c8a-4102-8a79-e1fe8aaa0d3e

**Comment by tom5454** [comment]
Issue with Pehkui: https://github.com/Virtuoel/Pehkui/issues/546
Run `/cpm scaling jump_height method attribute`. This switches the jump height scaler to use the attribute system.
