### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by FroogyKing** [tom5454/CustomPlayerModels#8]
I export the model and upload the skin but it doesn't work and there is no change to my player in game.

Can you give a more detailed explanation or a video on how to apply the models please?

**Comment by Terravolt14** [comment]
same

**Comment by tom5454** [comment]
Can you post your minecraft log?

**Comment by no-space** [comment]
Here's my own log with the same issue. Forge, no other mods installed:
https://pastebin.com/sVWxe3ax

**Comment by tom5454** [comment]
Can you post your skin file, that you exported?

**Comment by no-space** [comment]
WIP file, no gist:
![test](https://user-images.githubusercontent.com/7141717/107480930-7fb77b00-6bd1-11eb-8684-c243d3c5be4e.png)

"Final" file, using gist:
![birdfinal](https://user-images.githubusercontent.com/7141717/107480837-5a2a7180-6bd1-11eb-8694-71a37f7189ab.png)

**Comment by tom5454** [comment]
I loaded up the final skin file and it loads as it should. What is your Minecraft Name, And did you use the launcher or the website to upload your skin?

**Comment by no-space** [comment]
My MC name is no_space. I've used both the website and the launcher to upload the skin, with no change. 

Could it be a MC/Forge version issue? I'm running MC 1.16.5 and Forge 36.0.15, I'd like to try the same setup you have to see if that resolves it.

**Comment by tom5454** [comment]
I managed to fix it. The issue was with vanilla's skin filter not properly copying transparent pixels, and it corrupted the model data.
