### ISSUE TITLE
[Suggestion] Button to remove body parts from an animation

### ISSUE THREAD

**Issue by BitBlitObviMormon** [tom5454/CustomPlayerModels#81]
I've created a custom non-additive running animation for my model and accidentally moved the head in the animation. I couldn't figure out a way to remove the head from the animation. Setting the position and rotation back to the model defaults doesn't appear to work and now the head won't turn to look at the cursor while running. Could a button or right-click menu be added to enable removing a part from an animation? I don't mean deleting the part or making it invisible, I mean making the part unaffected by an animation which is especially important for animations that use absolute instead of relative coordinates.

![Player Model](https://media.discordapp.net/attachments/811530478698889267/844721745780932608/Minecraft__1.16.5_5_19_2021_4_34_40_PM.png)

**Comment by GrapeseedStudios** [comment]
good idea, and also that model terrifies the life out of me, but fantastic texture work!
