### ISSUE TITLE
How do I dowload my skin as jpg?

### ISSUE THREAD

**Issue by Noobrot** [tom5454/CustomPlayerModels#88]
I tried editing my skin with paint.net but the format was sadly cpmprojekt which pant.net obviously doesnt support.

**Comment by Noobrot** [comment]
png would also work btw

**Comment by BitBlitObviMormon** [comment]
If you uploaded it to Minecraft.net then you can get it here:
https://minecraftskinstealer.com/
... and anyone's skin for that matter...
