### ISSUE TITLE
game crashes on launch

### ISSUE THREAD

**Issue by XezianInfinite** [tom5454/CustomPlayerModels#93]
game immediately returned to launcher and gave me this message
The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1

i have used an earlier version of the mod in the past for a 1.17 snapshot but completely removed it from my folder
i have other mods including
entity culling
optifabric
and simple voice chat

does anyone know what's causing this

**Comment by tom5454** [comment]
Please post your full crash report and minecraft log. Also try it without optifabric.

**Comment by tom5454** [comment]
Duplicate of #95
